alphagov/accessibility-monitoring-platform

accessibility_monitoring_platform/apps/audits/templates/audits/all_issues.html
accessibility_monitoring_platform/apps/reports/utils.py

Trello card [#833](https://trello.com/c/jlXhP8Ys/833-report-issues-detected-by-axe-design-needed).

833: Capitalise Deque Axe; Hide description of manual tests.

---

package-lock.json
package.json

Trello card [#876](https://trello.com/c/rRXSx41w/876-update-to-gds-design-system-version-430).

876: Upgrade GDS Design System to version 4.3.0

---

stack_tests/smoke_tests/test_1.py

Trello card [#882](https://trello.com/c/kAJl5GKu/882-fix-devops-scripts-following-changes-to-pipenv).

882: Fix smoke test

---

__tests__/audits_check_filter.spec.js
__tests__/audits_copy_error.spec.js
__tests__/audits_copy_report.spec.js
__tests__/audits_retest_check_filter.spec.js
__tests__/common_field_link_button.spec.js
__tests__/mardown_preview.spec.js
__tests__/populate_date.spec.js
common/static/js/audits_check_filter.js
common/static/js/audits_copy_error.js
common/static/js/audits_copy_report.js
common/static/js/audits_retest_check_filter.js
common/static/js/common_field_link_button.js
common/static/js/markdown_preview.js
common/static/js/populate_date.js
package.json
pulp/helpers/recursively_copy.js

Trello card [#865](https://trello.com/c/aT5w7RzY/865-update-js-with-standard-js-style-guide).

865: User StandardJS formatting

---

accessibility_monitoring_platform/apps/audits/templates/audits/audit_detail.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/urls.py
accessibility_monitoring_platform/apps/audits/views.py

Trello card [#877](https://trello.com/c/ed2wKcxS/877-remove-delete-test-functionality-from-platform).

877: Remove delete and restore test from UI

---

Pipfile
Pipfile.lock
accessibility_monitoring_platform/apps/audits/templates/audits/forms/report_text.html

Trello card [#871](https://trello.com/c/0qY81umI/871-update-django-to-41).

871: Upgrade Django to version 4.1.

---

accessibility_monitoring_platform/apps/common/context_processors.py
accessibility_monitoring_platform/apps/common/tests/test_context_processors.py
accessibility_monitoring_platform/templates/base.html

Trello card [#892](https://trello.com/c/zVqxwmPV/892-fix-non-production-watermarks).

892: Fix non-production watermarks

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/report_text.html

Trello card [#897](https://trello.com/c/Zk7NwdLc/897-axe-in-report-text).

897: Capitalise Axe in How we checked on report text

---

__tests__/audits_check_filter.html
__tests__/audits_retest_check_filter.html
__tests__/js-enabled.spec.js
accessibility_monitoring_platform/templates/base.html
common/static/js/js-enabled.js
common/static/scss/_global.scss
common/static/scss/_report.scss
common/templates/reports_common/accessibility_report_container.html
report_viewer/templates/base.html

Trello card [#890](https://trello.com/c/QxFgGIIt/890-print-button-shows-when-javascript-disabled).

890: Show print button in report only when Javascript is enabled

---

Pipfile
Pipfile.lock
accessibility_monitoring_platform/apps/reports/tests/test_utils.py
accessibility_monitoring_platform/apps/reports/utils.py

Trello card [#836](https://trello.com/c/IuSKtzd0/836-remove-global).

836: Remove global; Pin setuptools to working version

---

accessibility_monitoring_platform/apps/audits/templates/audits/all_issues.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/report_text.html
accessibility_monitoring_platform/apps/reports/utils.py

Trello card [#985](https://trello.com/c/u68fYtxE/895-put-found-by-deque-axe-in-boilerplate).

895: Add Issue found by Dequeu Axe to boilerplate

---

accessibility_monitoring_platform/templates/base.html
common/static/js/js-enabled.js
common/templates/reports_common/accessibility_report_container.html
report_viewer/templates/base.html

Trello card [#903](https://trello.com/c/y1WwetTV/903-dashboard-needs-js-enabled-class-in-body)

903: Dashboard needs js-enabled class on body tag

---

accessibility_monitoring_platform/apps/cases/templates/cases/details/report_details.html
accessibility_monitoring_platform/apps/cases/templates/cases/forms/qa_process.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_steps.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/common/context_processors.py
accessibility_monitoring_platform/apps/common/templates/common/phase_banner.html
accessibility_monitoring_platform/apps/common/tests/test_context_processors.py
accessibility_monitoring_platform/apps/reports/templates/reports/helpers/s3_report_notification.html
accessibility_monitoring_platform/apps/reports/tests/test_utils.py
accessibility_monitoring_platform/apps/reports/utils.py
accessibility_monitoring_platform/settings/base.py
accessibility_monitoring_platform/templates/base.html
accessibility_monitoring_platform/templates/footer.html
cf_manifest/manifest-prod.yml
cf_manifest/manifest-test.yml
deploy_feature_to_paas/manifest_template.txt
report_viewer/settings/base.py

Trello card [#898](https://trello.com/c/2PZPuhwf/898-remove-domain-names-from-source-code).

898: Remove domain names from code

---

report_viewer/apps/viewer/tests.py
report_viewer/apps/viewer/views.py

Trello card [#912](https://trello.com/c/pHHAY4Bk/912-raise-log-warning-if-the-s3-bucket-fails-to-retrieve-report).

912: Warn when report not found in S3

---

accessibility_monitoring_platform/apps/reports/templates/reports/report_detail.html
common/templates/reports_common/accessibility_report_v1_0_0__20220406.html
common/templates/reports_common/helpers/table_issues.html

Trello card [#916](https://trello.com/c/dUJ1LD6u/916-check-fix-accessibility-issue-in-reports).

916: Make table header ids and cell headers attribute values consistent.

---

common/static/scss/_global.scss

Trello card [#920](https://trello.com/c/Jt8YIq9D/920-bullet-points-missing-in-report-issues).

920: Render lists inside report tables normally.

---

accessibility_monitoring_platform/apps/audits/utils.py
report_viewer/apps/viewer/tests.py

Trello card [#926](https://trello.com/c/Bd1kXYcF/926-only-update-checkresult-if-a-change-has-been-made).

926: Save test results only when changed.

---

accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_steps.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
report_viewer/apps/viewer/tests.py

Trello card [#873](https://trello.com/c/iEuk6cLf/873-add-link-to-the-websites-accessibility-statement-in-frequently-used-links).

873: Add link to accessibility statement.

---

accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/views.py
accessibility_monitoring_platform/apps/overdue/utils.py
stack_tests/integration_tests/test_1.py

Trello card [#933](https://trello.com/c/8nCBEX6k/933-default-methodologies-to-platform).

933: Default testing and report methodologies to platform.

---

accessibility_monitoring_platform/apps/users/tests/test_views.py
accessibility_monitoring_platform/settings/base.py

Trello card [#935](https://trello.com/c/oxMMzIZp/935-otp-token-email).

935: Change OTP token email subject line.

---

accessibility_monitoring_platform/apps/reports/templates/reports/report_confirm_refresh.html
accessibility_monitoring_platform/apps/reports/templates/reports/report_detail.html
accessibility_monitoring_platform/apps/reports/templates/reports/report_publisher.html
accessibility_monitoring_platform/apps/reports/tests/test_views.py
accessibility_monitoring_platform/apps/reports/views.py

Trello card [#936](https://trello.com/c/3Y6q8Qmz/936-reset-report-button-should-return-to-page-it-was-submitted-on).

936: Return to origin after report reset.

---

accessibility_monitoring_platform/apps/audits/models.py
common/templates/reports_common/accessibility_report_container.html

Trello card [#951](https://trello.com/c/LruddT7d/951-remove-report-a-problem-from-pdf-report).

951: Hide print button and feedback form in report print preview.

---

accessibility_monitoring_platform/apps/audits/templates/audits/helpers/nav_contents.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/nav_steps.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_nav_contents.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_nav_steps.html

Trello card [#954](https://trello.com/c/MFk76aSb/954-fix-sublist-structures).

954: Fix sublists.

---

accessibility_monitoring_platform/apps/reports/templates/reports/report_confirm_publish.html
accessibility_monitoring_platform/apps/reports/templates/reports/report_confirm_refresh.html

Trello card [#953](https://trello.com/c/RbMB95Fi/953-fix-report-publisher-breadcrumb).

953: Fix breadcrumbs.

---

accessibility_monitoring_platform/apps/audits/templates/audits/details/pages.html
accessibility_monitoring_platform/apps/audits/templates/audits/details/retest_pages.html
accessibility_monitoring_platform/apps/cases/templates/cases/forms/report_details.html
stack_tests/integration_tests/test_1.py

Trello card [#960](https://trello.com/c/x1zMy0LY/960-wcag-unique-ids-in-accordion).

960: Make ids in accordions unique

---

accessibility_monitoring_platform/apps/cases/utils.py

Trello card [#842](https://trello.com/c/DstyxvbL/842-equality-bodies-csv-change-export-order-names).

842: Rejig columns in equality body CSV export

---

report_viewer/apps/viewer/views.py

Trello card [#967](https://trello.com/c/TLufM2sU/967-remove-duplicate-reports-from-report-model)

967: Use report from case in viewer

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/cases/views.py

[#958](https://trello.com/c/n3Y6o4cm/958-wcag-two-search-fields-on-search-page).

958: Make unique the two search fields on the Search page

---

accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/views.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/reports/tests/test_views.py
accessibility_monitoring_platform/apps/reports/views.py

Trello card [#969](https://trello.com/c/eAxJTkP5/969-prevent-creation-of-duplicate-reports).

969: Prevent creation of more than one report or test per case

---

accessibility_monitoring_platform/apps/common/templates/common/metrics/breadcrumbs.html
accessibility_monitoring_platform/apps/common/templates/common/metrics/nav_steps.html
accessibility_monitoring_platform/apps/common/templates/common/metrics/overview.html
accessibility_monitoring_platform/apps/common/tests/test_views.py
accessibility_monitoring_platform/apps/common/urls.py
accessibility_monitoring_platform/apps/common/views.py
accessibility_monitoring_platform/templates/navbar.html

Trello card [#972](https://trello.com/c/9smXUI3z/972-make-a-skeleton-app-of-the-platform-metrics-page).

972: Add platform metrics overview page.

---

common/static/scss/_global.scss

Trello card [#977](https://trello.com/c/M5Ke5Waa/977-make-watermarks-accessible).

977: Make prototype and test platform watermarks more visible.

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#962](https://trello.com/c/g0Hzgr8i/962-add-is-complaint-to-advance-search-design-attached).

962: Add complaint filter to cases search page.

---

report_viewer/templates/500.html

Trello card [#970](https://trello.com/c/p0uQYUO9/970-create-500-page-for-the-report-viewer).

970: Add 500.html page for errors.

---

accessibility_monitoring_platform/apps/audits/templates/audits/helpers/nav_steps.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_nav_steps.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_steps.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/status_requirements.html
accessibility_monitoring_platform/templates/navbar.html

Trello card [#966](https://trello.com/c/t9Qg5jQv/966-add-status-requirements-to-testing-ui-design-attached).

966: Add Status requirements to right column on Testing and Retesting UI

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/utils.py

Trello card [#994](https://trello.com/c/LqILlnbC/994-restore-retest-disproportionate-burden-to-csv).

994: Add testing and retesting disproportionate burden data to CSV.

---

accessibility_monitoring_platform/apps/audits/forms.py
accessibility_monitoring_platform/apps/audits/templates/audits/forms/page_checks.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_page_checks.html

Trello card [#988](https://trello.com/c/8LKxtsxM/988-give-wcag-filter-a-label-design-attached).

988: Add WCAG definition filter input field label.

---

accessibility_monitoring_platform/apps/cases/templates/cases/emails/twelve_week_correspondence_email.html
common/static/scss/_global.scss

Trello card [#1001](https://trello.com/c/UED7mgvL/1001-refine-12-week-email-template).

1001: Refine email template based on user feedback.

---

accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/templates/cases/details/report_details.html
accessibility_monitoring_platform/apps/cases/templates/cases/forms/qa_process.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/status_requirements.html
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/reports/templates/reports/helpers/s3_report_notification.html

Trello card [#1000](https://trello.com/c/nbVmwuth/1000-add-published-report-to-equalities-body-export).

1000: Add published report url to equalities bodies export CSV.

---

accessibility_monitoring_platform/apps/reports/templates/reports/report_publisher.html

Trello card [#986](https://trello.com/c/lJh9hS3K/986-add-edit-test-link-to-report-generator)

986: Add button to link to test UI from report publisher.

---

accessibility_monitoring_platform/apps/audits/forms.py
accessibility_monitoring_platform/apps/audits/templates/audits/forms/statement_1.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/views.py
accessibility_monitoring_platform/apps/common/form_extract_utils.py

Trello card [#1012](https://trello.com/c/78KZlE4i/1012-add-contacts-field-in-statement-assessment).

1012: Add add contact fields to Accessibility statement Pt. 1.

---

package-lock.json
package.json

Trello card [#1023](https://trello.com/c/Jn2s0kKA/1023-upgrade-gds-design-system-to-v440).

1023: Upgrade GDS design system to v4.4.0.

---

accessibility_monitoring_platform/apps/common/chart.py
accessibility_monitoring_platform/apps/common/metrics.py
accessibility_monitoring_platform/apps/common/templates/common/metrics/case.html
accessibility_monitoring_platform/apps/common/templates/common/metrics/chart.svgt
accessibility_monitoring_platform/apps/common/templates/common/metrics/policy.html
accessibility_monitoring_platform/apps/common/templates/common/metrics/table.html
accessibility_monitoring_platform/apps/common/tests/test_chart.py
accessibility_monitoring_platform/apps/common/tests/test_metrics.py
accessibility_monitoring_platform/apps/common/tests/test_views.py
accessibility_monitoring_platform/apps/common/views.py

Trello card [#1024](https://trello.com/c/zAlvcb5c/1024-add-labels-to-charts).

1024: Add line labels to charts.

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/tests/test_forms.py
stack_tests/integration_tests/cypress/e2e/new_case_test_report.cy.js

Trello card [#1031](https://trello.com/c/PhhXUIUe/1031-remove-choice-of-methodologies).

1031: Remove testing and report methodologies from UI.

---

accessibility_monitoring_platform/apps/common/page_title_utils.py
accessibility_monitoring_platform/apps/common/templates/common/settings/more_information.html
accessibility_monitoring_platform/apps/common/templates/common/settings/nav_steps.html
accessibility_monitoring_platform/apps/common/tests/test_views.py
accessibility_monitoring_platform/apps/common/urls.py
accessibility_monitoring_platform/apps/common/views.py
stack_tests/integration_tests/cypress/e2e/axe.cy.js

Trello card [#1041](https://trello.com/c/2XswqpUI/1041-show-more-information-about-monitoring-text).

1041: Add more information about monitoring page to platform.

---

package-lock.json
package.json

Trello card [#1058](https://trello.com/c/YNilxsmM/1058-update-to-gds-design-system-version-441).

1058: Update GDS Design System to version 4.4.1.

---

accessibility_monitoring_platform/apps/cases/migrations/0046_populate_case_events.py

Trello card [#1054](https://trello.com/c/51Oo92gZ/1064-case-event-history-deploy).

1064: Make migration more memory efficient.

---

stack_tests/smoke_tests/cypress/e2e/case.cy.js

Trello card [#1064](https://trello.com/c/51Oo92gZ/1064-fix-case-event-history-deploy).

1064: Fix smoke test.

---

accessibility_monitoring_platform/apps/cases/migrations/0046_populate_case_events.py
stack_tests/smoke_tests/cypress/e2e/case.cy.js

* Fix smoke test. [#1064](https://trello.com/c/51Oo92gZ/1064-fix-case-event-history-deploy)

v0.4.50 - Fix smoke test

---

.gitignore
accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/urls.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1063](https://trello.com/c/kO2AwHBt/1063-add-export-feedback-survey-export).

1063: Add feedback survey export.

---

accessibility_monitoring_platform/apps/common/tests/test_views.py
accessibility_monitoring_platform/apps/common/views.py

Trello card [#1067](https://trello.com/c/M6SwB5V0/1067-policy-metrics-headers).

1067: Update policy metrics chart headers.

---

__tests__/audits_retest_check_filter.spec.js
common/static/js/audits_retest_check_filter.js

Trello card [#1072](https://trello.com/c/OadZfpBt/1072-not-retested-filter-doesnt-work).

1072: Fix filtering of 'Not retested' checks.

---

accessibility_monitoring_platform/apps/cases/templates/cases/twelve_week_correspondence_email.html

Trello card [#1076](https://trello.com/c/ZpdnQn6U/1076-remove-12-week-signature).

1076: Remove signature from 12-week email template.

---

__tests__/markdown_preview.spec.js
accessibility_monitoring_platform/apps/common/tests/test_templatetags.py
accessibility_monitoring_platform/apps/reports/tests/test_utils.py
common/static/js/markdown_preview.js

Trello card [#1081](https://trello.com/c/mgzv5bSy/1081-autoescape-html).

1091: Autoescape (HTML) text entered by users.

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/templates/cases/forms/create.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py

Trello card [#1085](https://trello.com/c/ufwkEyEy/1085-add-repeat-case-field-to-create-case-form-design-attached).

1085: Allow user to enter previous case url on create.

---

accessibility_monitoring_platform/apps/cases/templates/cases/helpers/view_initial_decision.html

Trello card [#1086](https://trello.com/c/VvQRWJoJ/1086-swap-initial-compliance-and-initial-statement-decision-design-attached).

1086: Swap initial compliance website and statement reminders.

---

__tests__/cases_copy_summary.spec.js
accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/templates/cases/forms/case_close.html
common/static/js/cases_copy_summary.js

Trello card [#1080](https://trello.com/c/VEPJDelr/1080-add-option-to-copy-text-from-summary-of-progress-made-from-public-sector-body-to-enforcement-recommendation-notes-design-attache).

1080: Add option to populate notes with summary text

---

accessibility_monitoring_platform/apps/audits/models.py
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/views.py

Trello card [#1099](https://trello.com/c/mPtvlLI0/1099-bug-with-save-and-continue-in-retest).

1099: Show error to user when Case has changed

---

accessibility_monitoring_platform/apps/reports/tests/test_views.py
accessibility_monitoring_platform/apps/reports/views.py

Trello card [#1098](https://trello.com/c/WFGg8Wqq/1098-list-of-unique-visits-is-not-ordered-by-time).

1098: Sort unique visits by most recent occurrance first

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_decision.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_website_decision.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/statement_decision.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/website_decision.html
accessibility_monitoring_platform/apps/audits/views.py

Trello card [#1113](https://trello.com/c/xLKimVvl/1113-fields-repeated-when-showing-version-error).

1113: Fix display of case error on audit pages

---

accessibility_monitoring_platform/apps/audits/templates/audits/details/pages.html
accessibility_monitoring_platform/apps/audits/templates/audits/details/retest_pages.html
accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/dashboard/templates/dashboard/list_view.html
package-lock.json
package.json
stack_tests/integration_tests/cypress/e2e/audit.cy.js
stack_tests/integration_tests/cypress/e2e/axe.cy.js
stack_tests/integration_tests/cypress/e2e/case.cy.js
stack_tests/integration_tests/cypress/e2e/dashboard.cy.js
stack_tests/integration_tests/cypress/e2e/new_case_test_report.cy.js
stack_tests/integration_tests/cypress/e2e/report.cy.js
stack_tests/integration_tests/cypress/e2e/retest.cy.js
stack_tests/integration_tests/cypress/package-lock.json
stack_tests/integration_tests/cypress/package.json
stack_tests/integration_tests/docker-compose.yml
stack_tests/smoke_tests/cypress/e2e/account.cy.js
stack_tests/smoke_tests/cypress/e2e/case.cy.js
stack_tests/smoke_tests/cypress/e2e/search.cy.js
stack_tests/smoke_tests/docker-compose.yml
stack_tests/smoke_tests/staging-platform.docker-compose.yml
stack_tests/smoke_tests_viewer/docker-compose.yml
stack_tests/smoke_tests_viewer/staging-viewer.docker-compose.yml

Trello card [#1110](https://trello.com/c/6DDTKaVA/1110-update-to-gds-design-system-version-450).

1110: Upgrade GDS Design System to version 4.5.0.

---

stack_tests/smoke_tests/cypress/e2e/account.cy.js
stack_tests/smoke_tests/cypress/e2e/case.cy.js

Trello card [#1110](https://trello.com/c/6DDTKaVA/1110-update-to-gds-design-system-version-450).

1110: Explicitly visit home page in smoke tests

---

.github/workflows/deploy-to-prod.yml

Trello card [#1110](https://trello.com/c/6DDTKaVA/1110-update-to-gds-design-system-version-450).

1110: Skip smoke tests

---

accessibility_monitoring_platform/apps/common/chart.py
accessibility_monitoring_platform/apps/common/tests/test_chart.py
accessibility_monitoring_platform/apps/common/tests/test_views.py
accessibility_monitoring_platform/apps/common/views.py

Trello card [#1128](https://trello.com/c/5MTjzUlp/1128-troubleshoot-and-fix-visualisations-for-proportion-of-websites-which-are-acceptable-and-proportion-of-accessibility-statements-w).

1128: Recalculate proportion of accessibility statements which are compliant

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1103](https://trello.com/c/ffYewD5Q/1103-add-ecni-ehrc-filter-to-advanced-search).

1103: Add cases filter on enforcement body

---

accessibility_monitoring_platform/apps/reports/templates/reports/helpers/nav_contents.html
accessibility_monitoring_platform/apps/reports/templates/reports/helpers/report_metadata_rows.html
accessibility_monitoring_platform/apps/reports/templates/reports/report_edit.html
accessibility_monitoring_platform/apps/reports/views.py

Trello card [#1136](https://trello.com/c/k25B7JyW/1136-remove-report-visits-log-subsection-from-edit-report).

1136: Remove report visits log section from Edit report page

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/cases/views.py
common/static/scss/_global.scss

Trello card [#1138](https://trello.com/c/uB9hzsEp/1138-update-case-search-page-design-attached).

1138: Swap columns on Case search page

---

accessibility_monitoring_platform/apps/cases/templates/cases/status_workflow.html

Trello card [#1160](https://trello.com/c/xEz9sECk/1160-add-links-to-complete-case).

1160: Add links to complete case to status workflow

---

accessibility_monitoring_platform/apps/audits/models.py
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/nav_steps.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_nav_steps.html
accessibility_monitoring_platform/apps/audits/tests/test_models.py
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/frequently_used_links.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_contents.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_steps.html
accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html
accessibility_monitoring_platform/apps/cases/tests/test_urls.py
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/urls.py
accessibility_monitoring_platform/apps/cases/views.py
accessibility_monitoring_platform/apps/common/admin.py
common/static/scss/_global.scss
stack_tests/integration_tests/cypress/e2e/axe.cy.js

Trello card [#1114](https://trello.com/c/GmGxC9pe/1114-make-it-easier-to-view-which-issues-are-remaining-and-add-a-table-template-design-attached).

1114: Add outstanding issues page

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1118](https://trello.com/c/nv418QTx/1118-add-test-start-date-to-date-filter-in-advanced-search).

1118: Add filter on test start date to cases search

---

accessibility_monitoring_platform/apps/cases/templates/cases/helpers/overview.html
accessibility_monitoring_platform/apps/reminders/templates/reminders/reminder_list.html

Trello card [#1145](https://trello.com/c/mBfgWxoV/1145-add-an-edit-option-in-reminders-list-design-attached).

1145: Add edit links to reminders list

---

__tests__/populate_date.spec.js
accessibility_monitoring_platform/apps/common/templates/common/amp_date_widget_template.html
accessibility_monitoring_platform/apps/common/tests/test_forms.py
accessibility_monitoring_platform/apps/reminders/forms.py
common/static/js/populate_date.js

Trello card [#1107](https://trello.com/c/dhTO1vhG/1107-add-javascript-widget-to-reminders-to-autopopulate-date-design-attached).

1107: Populate date fields with future dates

---

accessibility_monitoring_platform/apps/audits/templates/audits/audit_detail.html
accessibility_monitoring_platform/apps/audits/templates/audits/audit_retest_detail.html
accessibility_monitoring_platform/apps/audits/templates/audits/details/retest_metadata.html
accessibility_monitoring_platform/apps/audits/templates/audits/details/retest_statement.html
accessibility_monitoring_platform/apps/audits/templates/audits/details/retest_statement_decision.html
accessibility_monitoring_platform/apps/audits/templates/audits/details/retest_website_decision.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_nav_contents.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_overview.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_page_comparison.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py
stack_tests/integration_tests/cypress/e2e/retest.cy.js

Trello card [#1156](https://trello.com/c/qNnEUhus/1156-update-retest-overview-page-with-new-design-design-attached).

1156: Restructure View 12-week retest page to use accordion

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/tests/test_views.py

Trello card [#1178](https://trello.com/c/drw5erMu/1178-add-case-updated-date-field-to-advanced-search).

1178: Add advanced search filter on case updated date

---

accessibility_monitoring_platform/apps/cases/models.py

Trello card [#1201](https://trello.com/c/ItdWznM2/1201-for-enforcement-consideration).

1201: Change label to 'For enforcement consideration'

---

accessibility_monitoring_platform/apps/audits/tests/test_models.py
accessibility_monitoring_platform/apps/cases/templates/cases/twelve_week_correspondence_email.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1203](https://trello.com/c/8ILumIhN/1203-show-issues-in-email-template).

1203: Use report issues tables in email template

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_decision.html

Trello card [#1204](https://trello.com/c/nQj9aE7u/1204-open-link-disabled).

1204: Enable open link widget on retest statement decision page

---

accessibility_monitoring_platform/apps/common/templates/common/frequently_used_links.html

Trello card [#1179](https://trello.com/c/vgESbVYe/1179-add-link-to-12-retest-in-outstanding-issues-needs-design).

1179: Add links to View test and 12-week rested to Frequently used links

---

accessibility_monitoring_platform/apps/audits/models.py
accessibility_monitoring_platform/apps/audits/tests/test_models.py
accessibility_monitoring_platform/apps/audits/views.py
stack_tests/integration_tests/cypress/e2e/audit.cy.js
stack_tests/integration_tests/cypress/e2e/new_case_test_report.cy.js

Trello card [#1192](https://trello.com/c/IfLdqbhA/1192-put-accessibility-statement-test-at-the-bottom-of-the-test-pages).

1192: Sort pages to end with PDFs followed by statement

---

package-lock.json
package.json

Trello card [#1189](https://trello.com/c/AIrOijyC/1189-upgrade-gds-design-system-to-460).

1189: Upgrade GDS Design System to 4.6.0

---

accessibility_monitoring_platform/apps/dashboard/templates/dashboard/dashboard.html
accessibility_monitoring_platform/apps/dashboard/tests/test_views.py

Trello card [#1209](https://trello.com/c/DtGTnEL4/1209-show-on-call-qa).

1209: Show on-call QA on home page regardless

---

accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py

Trello card [#1180](https://trello.com/c/2XvEq0t9/1180-add-12-week-retest-info-to-outstanding-issues).

1180: Show results of retest on outstanding issues page

---

accessibility_monitoring_platform/apps/cases/templates/cases/case_detail.html
accessibility_monitoring_platform/apps/cases/tests/test_urls.py
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/urls.py
accessibility_monitoring_platform/apps/cases/views.py
accessibility_monitoring_platform/apps/reports/utils.py

Trello card [#1219](https://trello.com/c/OkFNCF95/1219-remove-export-to-csv-button-at-case-level).

1219: Remove CSV export from View case page

---

accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/overview.html
accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html
accessibility_monitoring_platform/apps/cases/tests/test_models.py
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/common/tests/test_utils.py
accessibility_monitoring_platform/apps/common/utils.py

Trello card [#1220](https://trello.com/c/fVeCqNH1/1220-add-website-and-statement-issues-to-case-overview-section-design-attached).

1220: Show outstanding issues in case overview

---

accessibility_monitoring_platform/apps/reports/templates/reports/helpers/overview.html
accessibility_monitoring_platform/apps/reports/templates/reports/report_publisher.html

Trello card [#1207](https://trello.com/c/LqIPAW5l/1207-add-link-to-published-report-in-the-top-row-of-links-design-attached).

1207: Add more prominent link to published report

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/common/templates/common/amp_field_two_column.html

Trello card [#1073](https://trello.com/c/bJnH0QIA/1073-add-help-text-to-12-week-update-requested-image-attached).

1073: Add extra line of help text to field

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/utils.py

Trello card [#1232](https://trello.com/c/NFlN3Jho/1232-move-feedback-survey-sent-field).

1232: Move survey sent field

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_pages.html

Trello card [#1259](https://trello.com/c/vLjYOsuw/1259-add-link-to-email-template).

1259: Add link to email template to 12-week pages comparison page

---

common/templates/reports_common/accessibility_report_v1_2_0__20230523.html

Trello card [#1262](https://trello.com/c/9JBmQjGb/1262-add-boilerplate-to-what-to-do-next).

1262: Update what to do next boilerplate text in report

---

accessibility_monitoring_platform/apps/common/models.py

Trello card [#1264](https://trello.com/c/AnihwcB9/1264-add-absolute-urls).

1264: Add more absolute urls

---

accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/tests/test_models.py
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/utils.py

Trello card 9#1268](https://trello.com/c/AN2sxnvo/1268-add-issues-percentage-to-csvs).

1268: Add percentage of issues fixed to CSV export

---

accessibility_monitoring_platform/apps/audits/models.py
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/statement_comparison.html
accessibility_monitoring_platform/apps/audits/tests/test_models.py
accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py

Trello card [#1269](https://trello.com/c/MesXBm51/1269-show-no-and-not-tested-outstanding-issues).

1269: Show only unfixed statement content check results on Outstanding issues page

---

accessibility_monitoring_platform/apps/audits/views.py
accessibility_monitoring_platform/apps/cases/views.py
accessibility_monitoring_platform/apps/common/templates/common/pagination_controls.html
accessibility_monitoring_platform/apps/common/tests/test_utils.py
accessibility_monitoring_platform/apps/common/utils.py

Trello card [#1270](https://trello.com/c/VuW13gmn/1270-broken-pagination).

1270: Fix pagination in Statement and WCAG issues lists

---

accessibility_monitoring_platform/apps/audits/models.py
accessibility_monitoring_platform/apps/audits/tests/test_models.py
accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html

Trello card [#1271](https://trello.com/c/VWVg6RnH/1271-split-outstanding-issues).

1271: Split contents of Outstanding issues page

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/utils.py

Trello card [#1272](https://trello.com/c/88lEt6FQ/1272-sort-unassigned-cards).

1272: Sort cases by default into unassigned first

---

accessibility_monitoring_platform/apps/common/templates/common/metrics/report.html
accessibility_monitoring_platform/apps/common/tests/test_views.py
accessibility_monitoring_platform/apps/common/views.py

Trello card [#1275](https://trello.com/c/n3XbOFTI/1275-remove-odt-report-metrics).

1275: Remove number of ODT from report metrics

---

report_viewer/apps/viewer/tests.py
report_viewer/apps/viewer/utils.py
report_viewer/templates/base.html

Trello card [#1278](https://trello.com/c/AKsaViPL/1278-update-report-viewer-outage-warning).

1278: Update report viewer outage warning

---

accessibility_monitoring_platform/settings/base.py

Trello card [#1274](https://trello.com/c/mSVxj0lk/1274-review-usage-of-django-axes).

1274: Update Django-axes configuration

---

accessibility_monitoring_platform/apps/common/tests/test_metrics.py
common/templates/reports_common/accessibility_report_v1_2_0__20230523.html

Trello card [#1289](https://trello.com/c/lgsv4g09/1289-misspelled-statment).

1289: Fix spelling of statment

---

accessibility_monitoring_platform/settings/base.py
aws_prototype/ecs_prepare_db.py
aws_prototype/tests/test_aws_secrets.py
aws_prototype/tests/test_create_dummy_account.py
aws_prototype/tests/test_ecs_prepare_db.py
report_viewer/settings/base.py

Trello card [#1310](https://trello.com/c/DhgteSqp/1310-unit-test-aws-prototype-scripts).

1310: Add tests for aws prototype scripts

---

copilot/environments/testenv/manifest.yml

Trello card [#1312](https://trello.com/c/AHQeQdm8/1312-watermarks-missing-from-test-platform).

1312: Show watermark on test platform

---

copilot/amp-svc/manifest.yml
copilot/environments/testenv/manifest.yml

Trello card [#1312](https://trello.com/c/AHQeQdm8/1312-watermarks-missing-from-test-platform).

1312: Show watermark on test platform redux

---

common/templates/reports_common/accessibility_report_v1_2_0__20230523.html

Trello card [#1316](https://trello.com/c/ddbkbKcZ/1316-check-if-report-text-is-baked-in-or-is-editable),

1316: Reword Your accessibility statement section in report

---

accessibility_monitoring_platform/apps/users/tests/test_views.py
accessibility_monitoring_platform/apps/users/views.py

Trello card [#1315](https://trello.com/c/Y9VcDzSp/1315-prevent-users-from-seeing-each-others-profiles).

1315: Prevent user from accessing other account details

---

accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/common/chart.py
accessibility_monitoring_platform/apps/common/metrics.py
accessibility_monitoring_platform/apps/common/templates/common/metrics/policy.html
accessibility_monitoring_platform/apps/common/tests/test_metrics.py
accessibility_monitoring_platform/apps/common/tests/test_utils.py
accessibility_monitoring_platform/apps/common/tests/test_views.py
accessibility_monitoring_platform/apps/common/utils.py
accessibility_monitoring_platform/apps/common/views.py

Trello card [#1314](https://trello.com/c/BI5BzT4k/1314-refactor-metrics-code).

1314: Refactor metrics code to make it easier to maintain

---

README.md

Trello card [#1333](https://trello.com/c/hncNrHMY/1333-update-readme).

1333: Fix index in README; Enable pre-commit checks.

---

aws_prototype/main.py
aws_prototype/tests/test_utils.py
aws_prototype/utils.py

Trello card [#1338](https://trello.com/c/24WvfMcB/1338-add-aws-tags-to-prototype-script).

1338: Add AWS resource tags to prototype script

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/utils.py
common/static/js/cases_copy_summary.js

Trello card [#1122](https://trello.com/c/uXaik10x/1122-change-enforcement-recommendation-notes-to-enforcement-recommendation-notes-including-exemptions).

1122: Add including exemptions to field label

---

accessibility_monitoring_platform/apps/common/models.py
accessibility_monitoring_platform/apps/common/templates/common/issue_report_list.html
accessibility_monitoring_platform/apps/common/urls.py
accessibility_monitoring_platform/apps/common/views.py

Trello card [#1352](https://trello.com/c/sET0GVJY/1352-add-user-feedback-to-platform-ui).

1352: Add page showing user feedback

---

.github/workflows/deploy-to-prod.yml
.github/workflows/deploy-to-test.yml

Trello card [#1356](https://trello.com/c/vBlbd1ys/1356-upgrade-github-actions).

1356: Upgrade actions/checkout@v2 to v3 in GitHub actions

---

accessibility_monitoring_platform/apps/common/admin.py
accessibility_monitoring_platform/settings/base.py
aws_prototype/main.py

Trello card [#1313](https://trello.com/c/t9inbkeF/1313-show-watermarks-on-prototypes).

1313: Show watermark in prototypes

---

amp_platform.DockerFile
amp_viewer.DockerFile
stack_tests/integration_tests/platform.Dockerfile

Trello card [#1370](https://trello.com/c/19VJrxUU/1370-update-nodejs-installation-scripts).

1370: Update scripts which install NodeJS to new process

---

accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/statement_feedback.html

Trello card [#1367](https://trello.com/c/10Mps6QC/1367-add-link-to-contact-page-on-feedback-and-enforcement-procedure-test-design-needed).

1367: Add link to contacts page to statement feedback

---

accessibility_monitoring_platform/apps/common/forms.py
accessibility_monitoring_platform/apps/common/page_title_utils.py
accessibility_monitoring_platform/apps/common/templates/common/bulk_url_search.html
accessibility_monitoring_platform/apps/common/templates/common/settings/nav_steps.html
accessibility_monitoring_platform/apps/common/tests/test_utils.py
accessibility_monitoring_platform/apps/common/tests/test_views.py
accessibility_monitoring_platform/apps/common/urls.py
accessibility_monitoring_platform/apps/common/utils.py
accessibility_monitoring_platform/apps/common/views.py

Trello card [#1385](https://trello.com/c/1usqX3oR/1385-bulk-case-search-using-urls).

1385: Add bulk search for Cases using URLs

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_1.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_2.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_decision.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/statement_1.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/statement_2.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/accessibility_statement_and_backup_link.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/accessibility_statement_link.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/statement_comparison.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/retest_statement_overview.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/statement_compliance.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/statement_custom.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/statement_feedback.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/statement_non_accessible.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/statement_preparation.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/statement_website.html
accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html
aws_prototype/main.py

Trello card [#1375](https://trello.com/c/JZaJWfW6/1375-update-outstanding-issues-table-design-design-attached).

1375: Redesign outstanding issues page

---

accessibility_monitoring_platform/apps/common/templates/common/amp_field_link_button.html
common/static/scss/_global.scss

Trello card [#1386](https://trello.com/c/4AJDbtIZ/1386-dynamic-url-links-broken).

1386: Remove inline styles

---

accessibility_monitoring_platform/apps/comments/forms.py

Trello card [#1389](https://trello.com/c/4wKC7iEi/1389-make-qa-comments-box-12-rows-high).

1389: Make QA comment textareas taller

---

accessibility_monitoring_platform/apps/common/admin.py
accessibility_monitoring_platform/apps/reminders/admin.py
accessibility_monitoring_platform/apps/reminders/views.py

Trello card [#1394](https://trello.com/c/pH7e0Qn2/1394-duplicate-reminders).

1394: Prevent same reminder being displayed twice; Fix admin search

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_comparison.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_nav_contents.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_nav_steps.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/views.py
stack_tests/integration_tests/cypress/e2e/new_case_test_report.cy.js

Trello card [#1399](https://trello.com/c/2yT1jUeH/1399-remove-12-week-accessibility-statement-compliance-decision-page).

1399: Hide 12-week accessibility statement compliance decision page

---

common/static/scss/_global.scss
common/templates/reports_common/accessibility_report_container.html

Trello card [#1402](https://trello.com/c/yrY5WTmu/1402-fix-layout-for-report-metadata-in-the-report).

1402: Stack report metadata in a single column

---

accessibility_monitoring_platform/apps/audits/templates/audits/helpers/statement_comparison_outstanding.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html

Trello card [#1415](https://trello.com/c/qODayAim/1415-partial-statement-comparison).

1415: Show all checks on 12-week statement comparison page

---

accessibility_monitoring_platform/apps/audits/models.py
accessibility_monitoring_platform/apps/audits/tests/test_models.py
accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html

Trello card [#1390](https://trello.com/c/CY3Pydum/1390-make-remaining-statement-issues-more-visible-in-the-outstanding-issues-page).

1390: Include new statement content errors in outstanding issues

---

accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/statement_feedback.html
accessibility_monitoring_platform/apps/common/templates/common/frequently_used_links.html

Trello card [#1419](https://trello.com/c/ES8GU0lI/1419-add-contacts-page-to-frequently-used-links).

1419: Add link to edit contacts page to frequently used links

---

accessibility_monitoring_platform/apps/common/templates/common/platform_checking.html
accessibility_monitoring_platform/apps/common/tests/test_utils.py
accessibility_monitoring_platform/apps/common/tests/test_views.py
accessibility_monitoring_platform/apps/common/utils.py
accessibility_monitoring_platform/apps/common/views.py

Trello card [#1422](https://trello.com/c/yetQvPn3/1422-add-button-to-delete-old-events).

1422: Add option to delete old events to platform checking page

---

accessibility_monitoring_platform/apps/cases/migrations/0063_set_statement_states.py

Trello card [#1439](https://trello.com/c/0VdkFzIm/1439-fix-migration-dependencies).

1439: Add dependency between cases data cleanup and most recent audit migration

---

accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1440](https://trello.com/c/YCbOzRUi/1440-platform-not-logging-case-changes-on-contact-details-page).

1440: Save case event on contact details page

---

common/templates/reports_common/accessibility_report_v1_2_0__20230523.html

Trello card [#1449](https://trello.com/c/sneFvQVG/1449-add-fields-to-case).

1449: Use website name in report

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
accessibility_monitoring_platform/apps/cases/templates/cases/forms/create.html
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/common/models.py

Trello card [#1452](https://trello.com/c/2eCxFDGd/1452-use-new-case-details-fields).

1452: Use new case details fields; Show website name all over the UI

---

accessibility_monitoring_platform/apps/common/forms.py
accessibility_monitoring_platform/apps/common/tests/test_forms.py

Trello card [#1461](https://trello.com/c/gmMitIup/1461-log-version-has-changed-errors).

1461: Log instances of changed since page loaded errors

---

accessibility_monitoring_platform/apps/audits/models.py

Trello card [#1459](https://trello.com/c/36xY7bzg/1459-add-14-inch-to-screen-size-options).

1459: Add 14-inch to screen size options

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1452](https://trello.com/c/2eCxFDGd/1452-use-new-case-details-fields).

1452: Add filtering of cases by subcategory

---

accessibility_monitoring_platform/templates/500.html
report_viewer/templates/500.html

Trello card [#1426](https://trello.com/c/2FKmhXAJ/1426-create-custom-error-page-for-viewer-and-platform-design-attached).

1426: Add custom 500 error pages for platform and viewer

---

accessibility_monitoring_platform/apps/dashboard/tests/test_utils.py

Trello card [#1471](https://trello.com/c/j0gqVGln/1471-case-changed-since-this-page-loaded-error)

1471: Make test compatible with python 3.11 (used in GitHub action)

---

accessibility_monitoring_platform/apps/cases/templates/cases/forms/qa_process.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1471](https://trello.com/c/j0gqVGln/1471-case-changed-since-this-page-loaded-error).

1471: Replace Add comment button with link

---

accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/views/twelve_week.py

Trello card [#1284](https://trello.com/c/bUvdg3Sx/1484-fix-statement-check-results-not-being-saved).

1484: Save 12-week statement check results BUGFIX

---

accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/utils.py

Trello card [#1488](https://trello.com/c/lidNuSxf/1488-rejig-feedback-survey-csv).

1488: Rejig feedback survey export CSV

---

accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/templates/cases/details/equality_body_retest.html
accessibility_monitoring_platform/apps/cases/tests/test_models.py

Trello card [#1498](https://trello.com/c/gh9EIMhw/1498-fix-number-retests).

1498: Fix number of retests shown on View case page

---

common/templates/reports_common/accessibility_report_v1_2_0__20230523.html

Trello card [#1395](https://trello.com/c/XfROceLs/1395-review-content-for-report-and-email-update-and-ensure-the-difference-between-the-statement-wcag-test-and-the-statement-content-i).

1395: Reword report template

---

amp_platform.DockerFile
amp_viewer.DockerFile
stack_tests/integration_tests/platform.Dockerfile

Trello card [#1517](https://trello.com/c/FTWQdOWx/1517-deploys-failing).

1517: Upgrade nodejs from 18 to 20

---

accessibility_monitoring_platform/apps/audits/templates/audits/details/retest_pages.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/twelve_week_pages_comparison.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_nav_contents.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/twelve_week_retest_nav_steps.html
accessibility_monitoring_platform/apps/audits/tests/test_utils.py
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/urls.py
accessibility_monitoring_platform/apps/audits/utils.py
accessibility_monitoring_platform/apps/audits/views/twelve_week.py
accessibility_monitoring_platform/apps/common/page_title_utils.py
stack_tests/integration_tests/cypress/e2e/axe.cy.js
stack_tests/integration_tests/cypress/e2e/twelve_week_retest.cy.js

Trello card [#1521](https://trello.com/c/9e7CDqTD/1521-group-errors-by-page-and-type-on-12-week-comparison).

1521: Add grouping by WCAG to 12-week pages comparison page

---

accessibility_monitoring_platform/apps/audits/models.py
accessibility_monitoring_platform/apps/audits/templates/audits/forms/equality_body_retest_comparison_update.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/equality_body_retest_page_comparison_table.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/views/equality_body.py

Trello card [#1496](https://trello.com/c/vBBDJMis/1496-add-filter-to-hide-fixed-issues-in-eb-retests).

1496: Group by page or WCAG in equality body retest comparison

---

accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/tests/test_models_status.py
accessibility_monitoring_platform/apps/dashboard/templates/dashboard/11_final_decision_due.html
accessibility_monitoring_platform/apps/dashboard/tests/test_views.py

Trello card [#1554](https://trello.com/c/gWKG0cw3/1554-add-reminders-link-final-decision-due-on-dashboard).

1554: Add view reminder links to Final decision due on home page

---

accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1558](https://trello.com/c/SnSJQLKb/1558-qa-comments-page-saving-blank-comments).

1558: Stop creating blank comments in QA comments page

---

accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1552](https://trello.com/c/2iGCisey/1552-show-warning-for-report-updating-when-case-details-update).

1552: Show notification when equality body updated and there is a published report

---

accessibility_monitoring_platform/apps/audits/templates/audits/helpers/nav_contents.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/nav_steps.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_nav_contents.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/twelve_week_retest_nav_steps.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/views/initial.py
accessibility_monitoring_platform/apps/audits/views/twelve_week.py

Trello card [#1566](https://trello.com/c/NOWQzXo5/1566-move-statement-compliance-decision-and-disproportionate-burden-into-main-list-in-test-ui).

1566: Move notification and statement compliance pages to main test UI

---

accessibility_monitoring_platform/apps/cases/templates/cases/case_detail.html

Trello card [#1584](https://trello.com/c/CeyNbyPI/1584-remove-single-quote-from-id-anchor).

1584: Remove extraneous quote from 12-week update requested anchor

---

package-lock.json
package.json

1585: Added three of specific dependencies mentioned by dependabot

---

accessibility_monitoring_platform/apps/cases/tests/test_views.py

Trello card [#1583](https://trello.com/c/4aIyTBNx/1583-implement-qa-process-v2-design-attached).

1583: Update mock_s3 to mock_aws

---

package.json

1585: Add dependencies to see if they are what dependabot is complaining about

---

package-lock.json
package.json

1585: Add dependencies to package-lock to see if they are what dependabot doesn't like

---

package.json

1585: Remove dependencies of dependencies

---

.github/workflows/deploy-to-test.yml

1585: Point test smoke tests at test platform and viewer

---

accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_content.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_contents.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
stack_tests/smoke_tests/cypress/e2e/case.cy.js

Trello card [#1593](https://trello.com/c/vL1MtBxq/1593-fix-smoke-tests).

1593: Fix smoke tests by fixing content link ids

---

accessibility_monitoring_platform/apps/cases/admin.py
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/qa_links.html

Trello card [#1601](https://trello.com/c/iafVvR5D/1601-fix-number-of-unread-comments).

1601: There is no such thing as an unread comment

---

accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/tests/test_models.py
accessibility_monitoring_platform/apps/cases/views.py
accessibility_monitoring_platform/apps/common/admin.py

TRello card [#1603](https://trello.com/c/IaWtpaCr/1603-fix-5-day-bug).

1603: Fix 5-day bug

---

accessibility_monitoring_platform/templates/navbar.html

Trello card [#1613](https://trello.com/c/g49rjXSV/1613-top-nav-menu-too-tall).

1613: Make top nav menu shorter

---

accessibility_monitoring_platform/apps/audits/admin.py

Trello card [#1614](https://trello.com/c/2NjtfpuH/1614-fix-checkresult-admin).

1614: Fix search in admin for CheckResult model

---

requirements.txt

Trello card [#1618](https://trello.com/c/kJG5evD4/1618-upgrade-django-to-v504).

1618: Upgrade Django to version 5.0.4

---

accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/common/templates/common/frequently_used_links.html
accessibility_monitoring_platform/apps/common/tests/test_view_section_utils.py
accessibility_monitoring_platform/apps/common/view_section_utils.py

Trello card [#1623](https://trello.com/c/BOQHmTxw/1623-add-psb-zendesk-to-frequent-links).

1623: Add PSB Zendesk tickets to Frequently used links

---

accessibility_monitoring_platform/apps/audits/models.py
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/numbers_of_issues.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/overview.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_overview.html
accessibility_monitoring_platform/apps/audits/tests/test_models.py
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/overview.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py

Trello card [#1616](https://trello.com/c/m9WMMlWB/1616-simplify-how-wcag-errors-are-aggregated-and-represented-design-attached).

1616: Simplify WCAG and Statement content issue totals

---

accessibility_monitoring_platform/apps/audits/models.py
accessibility_monitoring_platform/apps/audits/tests/test_models.py

Trello card [#1629](https://trello.com/c/sroqxdxx/1629-hide-errors-on-form-pages).

1629: Hide errors if page is_contact_page is set

---

accessibility_monitoring_platform/apps/audits/models.py
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/numbers_of_issues.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/common/tests/test_utils.py
accessibility_monitoring_platform/apps/common/utils.py

Trello card [#1628](https://trello.com/c/ZOUdxj4S/1628-add-percentages-to-wcag-summary).

1628: Show percentage of WCAG issues fixed

---

requirements.txt

Trello card [#1631](https://trello.com/c/KMIv814u/1631-dependabot-hates-sqlparse).

1631: Upgrade dependencies to address issues reported by dependabot

---

accessibility_monitoring_platform/apps/audits/admin.py
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/archive_nav_contents.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/utils.py

Trello card [#1632](https://trello.com/c/vUcd2CiW/1632-archived-cases-revived-by-ehrc).

1632: Update View case page to cope with archived cases revived by EHRC

---

accessibility_monitoring_platform/apps/cases/utils.py

Trello card [#1635](https://trello.com/c/vSyE4qce/1635-broken-link-to-report-publisher-on-view-case).

1635: Fix report-related links on View case

---

accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/utils.py

Trello card [#1637](https://trello.com/c/ap6nklEL/1637-wrong-ticks-on-12-week-retest).

1637: Use correct complete dates for 12-week retest pages

---

accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/urls.py
accessibility_monitoring_platform/apps/audits/views/base.py
accessibility_monitoring_platform/apps/audits/views/initial.py
accessibility_monitoring_platform/apps/audits/views/twelve_week.py

Trello card [#1638](https://trello.com/c/aXxT0PQN/1638-add-missing-event-tracking).

1638: Add event tracking

---

accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/views/equality_body.py

Trello card [#1640](https://trello.com/c/LoxI4Vs6/1640-equality-body-retest-save-and-continue).

1640: Equality body retest; Statement overview; Save and continue

---

accessibility_monitoring_platform/apps/cases/templates/cases/helpers/archive_nav_contents.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_steps.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/utils.py

Trello card [#1656](https://trello.com/c/rkplMnj2/1656-reflect-the-same-post-case-steps-in-the-side-nav-bar-as-the-case-overview-page).

1656: Show latest post case UI in all case variants.

---

.pre-commit-config.yaml
accessibility_monitoring_platform/apps/audits/templates/audits/forms/pages.html

Trello card [#1660](https://trello.com/c/t7e4m0Dl/1660-location-field-not-shown-for-form-page).

1660: Show location field for form page in UI

---

accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/cases/views.py
accessibility_monitoring_platform/apps/common/views.py
accessibility_monitoring_platform/apps/reports/tests/test_utils.py
accessibility_monitoring_platform/apps/reports/utils.py

Trello card [#1661](https://trello.com/c/cX41ThU4/1661-create-outstanding-issues-email-template-and-replace-the-middle-column-with-12-week-notes).

1661: Add retest to email template context

---

accessibility_monitoring_platform/apps/cases/templates/cases/forms/retest_overview.html
accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html

Trello card [#1662](https://trello.com/c/NktrXG83/1662-add-email-templates-once-email-template-system-has-been-deployed).

1662: Add email template list to outstanding issues and retest overview pages

---

accessibility_monitoring_platform/apps/cases/views.py
accessibility_monitoring_platform/apps/common/management/commands/backup_email_templates.py
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/12-week-request.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/12-week-update-request.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/equality-body-retest.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/no-response-email-one-month.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/no-response-email-seven-day.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/outstanding-issues.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/sending-report-email-no-accessibility-statement-only.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/sending-report-email-platform.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/sending-report-email-public-complaint.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/sending-report-email-via-platform.html
accessibility_monitoring_platform/apps/common/views.py
common/static/scss/_global.scss

Trello card [#1662](https://trello.com/c/NktrXG83/1662-add-email-templates-once-email-template-system-has-been-deployed).

1662: Add command to backup email templates from database to codebase

---

accessibility_monitoring_platform/apps/cases/templates/cases/helpers/correspondence_overview.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py

Trello card [#1654](https://trello.com/c/vE2OhiOh/1654-add-zendesk-tickets-to-the-correspondence-overview-design-attached).

1654: List PSB Zendesk tickets in correspondence overview

---

accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1670](https://trello.com/c/p5nH313T/1670-include-only-unfixed-in-12-week-email).

1670: Include only unfixed checks in email

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/equality_body_retest_disproportionate_burden.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/equality_body_retest_statement_decision.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/equality_body_retest_statement_results.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_1.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_2.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_decision.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/twelve_week_disproportionate_burden.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/statement_comparison.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/statement_pages_eb_retest.html
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/statement_pages_twelve_week.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_compliance.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_custom.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_feedback.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_non_accessible.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_overview.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_preparation.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_website.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/retest_statement_compliance.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/retest_statement_feedback.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/retest_statement_non_accessible.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/retest_statement_other.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/retest_statement_overview.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/retest_statement_preparation.html
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/retest_statement_website.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py

Trello card [#1651](https://trello.com/c/McdNoyZH/1651-update-edit-links-for-statement-links-to-go-to-12-week-page-when-in-the-12-week-process).

1651: Add retest-stage-specific links to statement pages

---

accessibility_monitoring_platform/apps/cases/templates/cases/helpers/correspondence_overview.html

Trello card [#1676](https://trello.com/c/5vcr8pQ3/1676-view-zendesk-tickets-in-new-tab).

1676: Open Zendesk tickets in new tab

---

accessibility_monitoring_platform/apps/reports/tests/test_views.py
accessibility_monitoring_platform/apps/reports/views.py

Trello card [#1684](https://trello.com/c/NPQCgwor/1684-filter-unique-report-visits-by-report).

1684: Restrict unique report visits to current case

---

accessibility_monitoring_platform/apps/cases/templates/cases/zendesk_tickets.html

Trello card [#1681](https://trello.com/c/GjNV5hGL/1681-move-summary-to-the-top-of-the-zendesk-ticket).

1681: Move Zendesk summary up

---

accessibility_monitoring_platform/apps/cases/templates/cases/emails/equality_body_retest_email.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1565](https://trello.com/c/iIaSvNpM/1565-add-retest-notes-to-the-ehrc-retest-email-template).

1565: Add retest notes to equality body retest email

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/models.py

Trello card [#1683](https://trello.com/c/QpR0D9qE/1683-move-survey-sent-field-to-case-details-section).

1683: Move feedback survey sent field to case details

---

accessibility_monitoring_platform/apps/common/views.py

Trello card [#1701](https://trello.com/c/e7UDwR28/1701-let-python-deal-with-weird-newline-characters-in-bulk-url-search).

1701: Let Python deal with funny newlines

---

accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/views.py
accessibility_monitoring_platform/apps/notifications/models.py
accessibility_monitoring_platform/apps/notifications/tests/test_models.py
accessibility_monitoring_platform/apps/notifications/tests/test_utils.py
accessibility_monitoring_platform/apps/notifications/tests/test_views.py
accessibility_monitoring_platform/apps/notifications/urls.py
accessibility_monitoring_platform/apps/notifications/utils.py
accessibility_monitoring_platform/apps/notifications/views.py

Trello card [#1694](https://trello.com/c/XZ49VRPV/1694-task-list-links).

1694: Change label on 12-week deadline option; Mark case tasks as seen; Sort read task in reverse

---

accessibility_monitoring_platform/apps/exports/templates/exports/export_detail.html
accessibility_monitoring_platform/apps/exports/tests/test_views.py
accessibility_monitoring_platform/apps/exports/urls.py
accessibility_monitoring_platform/apps/exports/views.py

Trello card [#1705](https://trello.com/c/KaazYtHn/1705-add-mark-all-ready-option-to-csv-managers).

1705: Add option to mark all Cases in an equality body export as ready

---

accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/urls.py
accessibility_monitoring_platform/apps/cases/views.py
accessibility_monitoring_platform/apps/comments/forms.py
accessibility_monitoring_platform/apps/comments/tests/test_utils.py
accessibility_monitoring_platform/apps/comments/utils.py
common/static/js/index.js

Trello card [#1710](https://trello.com/c/lgGvzdEh/1710-disable-double-clicking-buttons).

1710: Disable double-clicking on buttons

---

stack_tests/smoke_tests/cypress/e2e/case.cy.js

Trello card [#1709](https://trello.com/c/FxpQp7Bh/1709-add-the-new-case-banner-and-remove-the-existing-subheader-and-case-nav-bar-content-design-attached).

1709: Fix smoke tests

---

accessibility_monitoring_platform/apps/users/templates/users/forms/create.html
accessibility_monitoring_platform/templates/registration/login.html
accessibility_monitoring_platform/templates/registration/password_reset_complete.html
accessibility_monitoring_platform/templates/registration/password_reset_confirm.html
accessibility_monitoring_platform/templates/registration/password_reset_done.html
accessibility_monitoring_platform/templates/registration/password_reset_form.html
accessibility_monitoring_platform/templates/two_factor/core/login.html
report_viewer/templates/footer.html

Trello card [#1712](https://trello.com/c/Z9zzYBfi/1712-remove-30px-padding-when-window-size-goes-below-1020px-width).

1712: Add `qovuk-width-container` class to pages where it is missing

---

accessibility_monitoring_platform/apps/reports/models.py
accessibility_monitoring_platform/apps/reports/tests/test_models.py
common/templates/reports_common/accessibility_report_v1_3_0__20240710.html

Trello card [#1721](https://trello.com/c/NZnIjWdn/1721-remove-some-references-to-cabinet-office).

1721: Remove some references to the Cabinet Office

---

accessibility_monitoring_platform/apps/audits/admin.py
accessibility_monitoring_platform/apps/cases/admin.py
accessibility_monitoring_platform/apps/exports/admin.py
accessibility_monitoring_platform/apps/notifications/admin.py
accessibility_monitoring_platform/apps/notifications/tests/test_views.py
accessibility_monitoring_platform/apps/notifications/views.py

Trello card [#1722](https://trello.com/c/eC4PMf7M/1722-show-other-users-task-list).

1722: Add option to show other users' Tasks

---

package-lock.json
requirements.txt

Trello card [#1720](https://trello.com/c/t8qkIphe/1720-upgrade-django-to-507).

1720: Upgrade Django to version `5.0.7`

---

accessibility_monitoring_platform/apps/audits/admin.py
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/urls.py
accessibility_monitoring_platform/apps/audits/views/equality_body.py
accessibility_monitoring_platform/apps/cases/templates/cases/forms/retest_overview.html

Trello card [#1724](https://trello.com/c/C644wDDj/1724-allow-user-to-delete-retest).

1724: Allow user to delete equality body-requested retest

---

accessibility_monitoring_platform/apps/cases/templates/cases/forms/review_changes.html

Trello card [#1729](https://trello.com/c/6iyGeKM8/1729-add-email-templates).

1729: Add email templates to Reviewing changes page

---

accessibility_monitoring_platform/apps/cases/templates/cases/forms/case_close.html
accessibility_monitoring_platform/apps/cases/templates/cases/forms/enforcement_recommendation.html
accessibility_monitoring_platform/apps/cases/templates/cases/forms/metadata.html
accessibility_monitoring_platform/apps/cases/templates/cases/forms/review_changes.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_details.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_details_text.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_steps.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/views.py
accessibility_monitoring_platform/apps/common/case_nav.py
accessibility_monitoring_platform/apps/common/tests/test_case_nav.py

Trello card [#1730](https://trello.com/c/52XXtcKO/1730-add-redesign-ui-closing-the-case).

1730: Add redesigned UI for navigating to Closing the case pages

---

accessibility_monitoring_platform/apps/cases/templates/cases/forms/enforcement_recommendation.html

Trello card [#1737](https://trello.com/c/lzyp9FvL/1737-add-zendesk-psb-tickets-to-enforcement-recommendation).

1737: Add PSB Zendesk tickets element to `Enforcement recommendation` page

---

accessibility_monitoring_platform/apps/common/context_processors.py
accessibility_monitoring_platform/apps/common/tests/test_utils.py
accessibility_monitoring_platform/apps/common/utils.py
accessibility_monitoring_platform/templates/base.html
common/static/scss/_global.scss

Trello card [#1735](https://trello.com/c/IkE2wL7r/1735-warn-users-when-session-about-to-expire).

1735: Warn users when their session is about to expire

---

accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1744](https://trello.com/c/0fs9FRQJ/1744-enable-new-case-nav-ui-fragments-on-psb-zendesk-pages).

1744: Show Case nav sections on PSB Zendesk pages

---

accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1744](https://trello.com/c/0fs9FRQJ/1744-enable-new-case-nav-ui-fragments-on-psb-zendesk-pages).

1744: Show Case nav sections on Status workflow

---

accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/views.py
accessibility_monitoring_platform/apps/common/case_nav.py

Trello card [#1746](https://trello.com/c/RLdczKey/1746-add-case-navigation-to-outstanding-issues-page).

1746: Add case navigation to Outstanding issues page

---

stack_tests/smoke_tests/cypress/e2e/case.cy.js

Trello card [#1731](https://trello.com/c/CuPSIFQN/1731-add-redesign-ui-correspondence).

1731: Fix smoke test

---

accessibility_monitoring_platform/apps/dashboard/templates/dashboard/8_in_probation_period.html

Trello card [#1758](https://trello.com/c/0plzhnZH/1758-fix-home-dashboard-links).

1758: Fix broken link on home page

---

accessibility_monitoring_platform/apps/dashboard/templates/dashboard/8_in_probation_period.html
stack_tests/smoke_tests/cypress/e2e/case.cy.js

* Fix broken link on home page ([home](https://platform.accessibility-monitoring.service.gov.uk/)) [#1758](https://trello.com/c/0plzhnZH/1758-fix-home-dashboard-links)

v0.6.108 - Fix broken link on home page

---

accessibility_monitoring_platform/apps/cases/templates/cases/helpers/correspondence.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/correspondence_overview_detail.html

Trello card [#1754](https://trello.com/c/1yhgPXUz/1754-show-correspondence-overview).

1754: Put correspondence overview back for now

---

accessibility_monitoring_platform/apps/cases/templates/cases/forms/review_changes.html

Trello card [#1754](https://trello.com/c/1yhgPXUz/1754-show-correspondence-overview).

1754: Add correspondence overview to Reviewing changes page

---

accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1760](https://trello.com/c/z8FS63tq/1760-fix-equality-body-metadata-save-continue).

1760: Fix Save and continue redirect on Equality body metadata page

---

accessibility_monitoring_platform/apps/cases/migrations/0006_enable_cores_process.py

Trello card [#1765](https://trello.com/c/s782haRP/1765-enable-correspondence-process-on-cases-where-no-contact-emails-sent).

1765: Enable the correspondence process for those Cases with notes or an unresponsive PSB

---

package-lock.json
requirements.txt

Trello card [#1757](https://trello.com/c/M6zng3id/1757-upgrade-django-to-51).

1757: Upgrade dependencies

---

accessibility_monitoring_platform/apps/dashboard/templates/dashboard/dashboard.html

Trello card [#1772](https://trello.com/c/vHeh3jKZ/1772-reverse-tab-order-of-buttons-on-home-page).

1772: Reverse tab order of buttons on Home page

---

report_viewer/templates/404.html

Trello card [#1766](https://trello.com/c/zmwHIfb0/1766-ammend-404-page-in-the-viewer-to-say-if-you-entered-a-web-address-check-it-is-correct-or-contact-the-auditor-who-sent-the-report).

1766: Amend text on 404 page

---

package-lock.json
package.json

Trello card [#1757](https://trello.com/c/M6zng3id/1757-upgrade-django-to-51).

1757: Upgrade gulp and its dependencies

---

accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1775](https://trello.com/c/ZfApNprw/1775-email-template-changes).

1775: Add 12_weeks_from_today to email template context

---

accessibility_monitoring_platform/apps/reports/admin.py

Trello card [#1777](https://trello.com/c/dU957T6K/1777-fix-reports-admin).

1777: Fix reports admin

---

accessibility_monitoring_platform/apps/cases/templates/cases/forms/four_week_followup_contact.html
accessibility_monitoring_platform/apps/cases/templates/cases/forms/one_week_followup_contact.html
accessibility_monitoring_platform/apps/cases/templates/cases/forms/request_initial_contact.html

Trello card [#1768](https://trello.com/c/5risU57v/1768-add-contact-details-chaser-fields-to-correspondence-overview).

1768: Add contact details element to chaser fields in Contact details

---

accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
common/static/scss/_global.scss

Trello card [#1779](https://trello.com/c/FsNCGHgU/1779-advanced-search-overlapping).

1779: Adjust select min-width which causes overlap

---

accessibility_monitoring_platform/templates/navbar.html

Trello card [#1780](https://trello.com/c/5tvpCDNF/1780-hide-from-screen-reader).

1780: Hide cosmetic list item from screen readers

---

accessibility_monitoring_platform/apps/audits/utils.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/common/sitemap.py
accessibility_monitoring_platform/apps/common/tests/test_view_section_utils.py
accessibility_monitoring_platform/apps/common/view_section_utils.py

Trello card [#1781](https://trello.com/c/8YhexryY/1781-use-strenum-instead-of-literal).

1781: Replace Literal type with StrEnum

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/test_summary.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/views/initial.py

Trello card [#1785](https://trello.com/c/XOx42XDV/1785-change-the-label-for-the-button-on-test-summary).

1785: Change the button label to match page header

---

accessibility_monitoring_platform/apps/audits/utils.py
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/common/templates/common/view_accordion/section.html
accessibility_monitoring_platform/apps/common/tests/test_view_section_utils.py
accessibility_monitoring_platform/apps/common/view_section_utils.py
stack_tests/integration_tests/cypress/e2e/axe.cy.js

Trello card [#1791](https://trello.com/c/QP9pkudo/1791-accordion-aria-error-on-view-case).

1791: Fix `aria-controls` Axe error on View case page

---

accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/common/models.py
accessibility_monitoring_platform/apps/dashboard/templates/dashboard/7_in_report_correspondence.html
accessibility_monitoring_platform/apps/dashboard/templates/dashboard/9_in_12_week_correspondence.html
accessibility_monitoring_platform/apps/notifications/models.py
accessibility_monitoring_platform/apps/notifications/tests/test_models.py
accessibility_monitoring_platform/apps/notifications/tests/test_utils.py
accessibility_monitoring_platform/apps/notifications/utils.py

Trello card [#1762](https://trello.com/c/csCNRaU0/1762-12-week-update-due-link-goes-to-manage-contact-details).

1762: Make Case correspondence properties links not labels

---

accessibility_monitoring_platform/templates/two_factor/_wizard_actions.html

Trello card [#1794](https://trello.com/c/JTsoMiUg/1794-fix-styling-on-sign-in).

1794: Add GDS Design System styling to links on Sign in page

---

stack_tests/smoke_tests/cypress/e2e/case.cy.js

Trello card [#1788](https://trello.com/c/Y0kdktWQ/1788-report-and-qa-ui-update).

1788: Fix smoke test

---

accessibility_monitoring_platform/apps/cases/forms.py

Trello card [#1798](https://trello.com/c/Dg7w2NqX/1798-change-field-order-on-edit-psb-zendesk-ticket-page).

1798: Swap order of fields on Edit PSB Zendesk ticket page

---

package-lock.json
requirements.txt

Trello card [#1803](https://trello.com/c/ltVEJmfV/1803-upgrade-django-to-512).

1803: Upgrade dependencies

---

accessibility_monitoring_platform/apps/notifications/tests/test_views.py
accessibility_monitoring_platform/apps/notifications/views.py

Trello card [#1806](https://trello.com/c/6MCf2Jz5/1806-update-reminder-user).

1806: Update reminder user to match current Case auditor

---

accessibility_monitoring_platform/apps/audits/models.py

Trello card [#1807](https://trello.com/c/roCczKgF/1807-pust-screen-sizes-in-ascending-order).

1807: Put screen sizes in ascending order; Default to 13-inch

---

__tests__/cases_search_in_case.spec.js
accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/statement_formset_form.html
accessibility_monitoring_platform/apps/cases/templates/cases/case_detail.html
accessibility_monitoring_platform/apps/cases/templates/cases/details/search_in_case.html
common/static/js/cases_search_in_case.js
stack_tests/integration_tests/cypress/e2e/case.cy.js
stack_tests/smoke_tests/cypress/e2e/case.cy.js

Trelo card [#1784](https://trello.com/c/nR0Ptinh/1784-fix-the-contents-list-case-overview)

1784: Move search within Case to top of View case page

---

stack_tests/integration_tests/cypress/e2e/case.cy.js
stack_tests/smoke_tests/cypress/e2e/case.cy.js

Trello card [#1733](https://trello.com/c/PD9i8Uq9/1733-archive-non-statement-content-checked-cases).

1733: Fix smoke tests

---

accessibility_monitoring_platform/apps/cases/templates/cases/case_detail.html

Trello card [#1784](https://trello.com/c/nR0Ptinh/1784-fix-the-contents-list-case-overview).

1784: Add post case content for archived cases

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_test_summary.html

Trello card [#1817](https://trello.com/c/YMg8JcpC/1817-show-12-week-statement-check-results-in-summary).

1817: Update edit links in 12-week retest summary pages

---

accessibility_monitoring_platform/apps/cases/templates/cases/case_detail.html
accessibility_monitoring_platform/apps/cases/templates/cases/details/search_in_case.html

Trello card [#1813](https://trello.com/c/97l7c7z6/1813-case-overview-and-view-and-search-all-case-data-pages).

1813: Place search results in one column

---

accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/notifications/tests/test_utils.py
accessibility_monitoring_platform/apps/notifications/utils.py

Trello card [#1813](https://trello.com/c/97l7c7z6/1813-case-overview-and-view-and-search-all-case-data-pages).

1813: User Case overdue_link on Tasks page

---

package-lock.json
requirements.txt

Trello card [#1831](https://trello.com/c/rV82fsmY/1831-upgrade-django-to-513).

1831: Upgrade Django to 5.1.3

---

accessibility_monitoring_platform/apps/common/templates/common/emails/backup/4-12-week-update-request.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/5b-outstanding-issues-12-week-retest-notes.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/7b-equality-body-retest-unfixed-issues.html

Trello card [#1832](https://trello.com/c/Mr5HYbNu/1832-backup-changes-to-email-templates).

1832: Backup email templates

---

accessibility_monitoring_platform/apps/common/metrics.py
accessibility_monitoring_platform/apps/common/tests/test_metrics.py
accessibility_monitoring_platform/apps/common/tests/test_views.py

Trello card [#1801](https://trello.com/c/gjKb7y0Z/1801-overhaul-metrics-in-platform).

1801: Add totals to metrics tables

---

accessibility_monitoring_platform/apps/cases/templates/cases/helpers/qa_links.html

Trello card [#1846](https://trello.com/c/YXHUWch4/1846-hide-link-to-non-existent-accessibility-statement).

1846: Hide link to accessibility statement if none exists

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/templates/cases/forms/create.html

Trello card [#1849](https://trello.com/c/vV42EyhJ/1849-switch-fields-on-case-metadata).

1849: Swap positions of Case URL and organisation name fields in UI

---

accessibility_monitoring_platform/apps/cases/templates/cases/case_detail.html
stack_tests/smoke_tests/cypress/e2e/case.cy.js

Trello card [#1813](https://trello.com/c/97l7c7z6/1813-case-overview-and-view-and-search-all-case-data-pages).

1813: Fix smoke tests; Archived cases no longer allow search on Case overview page

---

amp_platform.DockerFile

Trello card [#1862](https://trello.com/c/RKT5WjvY/1862-periodically-clear-django-sessions).

1862: Clear Django sessions as part of deploys to production

---

accessibility_monitoring_platform/templates/navbar.html

Trello card [#1865](https://trello.com/c/5W1TJlTZ/1865-hide-logged-in-user-from-screenreaders).

1865: Hide logged in user name from screen readers

---

package-lock.json
requirements.txt

Trello card [#1868](https://trello.com/c/aQtCy6qF/1868-upgrade-platform-dependencies).

1868: Upgrade dependencies

---

package-lock.json

Trello card [#1868](https://trello.com/c/aQtCy6qF/1868-upgrade-platform-dependencies).

1868: Upgrade integration test dependencies

---

accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/tests/test_models.py
accessibility_monitoring_platform/apps/notifications/models.py
accessibility_monitoring_platform/apps/notifications/templates/notifications/helpers/read_reminders.html
accessibility_monitoring_platform/apps/notifications/templates/notifications/reminder_task_create.html
accessibility_monitoring_platform/apps/notifications/templates/notifications/reminder_task_update.html
accessibility_monitoring_platform/apps/notifications/templates/notifications/task_list.html
accessibility_monitoring_platform/apps/notifications/tests/test_models.py
accessibility_monitoring_platform/apps/notifications/tests/test_views.py
accessibility_monitoring_platform/apps/notifications/views.py

Trello card [#1863](https://trello.com/c/5WT4xpng/1863-add-reminders-history).

1863: Add history to reminders

---

accessibility_monitoring_platform/apps/audits/templates/audits/helpers/test_summary_statement_content.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/cases/tests/test_views.py

Trello card [#1872](https://trello.com/c/xGzagXpB/1872-test-summary-pages-crash).

1872: Fix edit URLs for custom statement issues on Test summary pages

---

accessibility_monitoring_platform/apps/common/templates/common/next_platform_page.html

Trello card [#1864](https://trello.com/c/mzzN868c/1864-implement-new-save-and-continue-component#comment-678fa42a7f3641279f21c21b).

1864: Reformat showing multiple possible next pages

---

accessibility_monitoring_platform/apps/cases/tests/test_views.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1873](https://trello.com/c/chzfFqhx/1873-show-both-next-pages-for-unresponsive-psb).

1873: Show both next pages on Unresponsive PSB page

---

prepare_local_db.py

Trello card [#1884](https://trello.com/c/uQwkkL5Z/1884-stale-live-snapshot-downloaded).

1884: Download latest live snapshot for local development

---

package-lock.json
requirements.txt
stack_tests/integration_tests/cypress/package-lock.json

Trello card [#1890](https://trello.com/c/KTe4Wz20/1890-upgrade-django-to-516).

1890: Upgrade Django to version 5.1.6

---

accessibility_monitoring_platform/apps/common/tests/test_sitemap.py
accessibility_monitoring_platform/apps/common/tests/test_views.py

Trello card [#1893](https://trello.com/c/BR4ERmxG/1893-fix-tests-of-report-an-issue).

1893: Check content of Report an issue page

---

accessibility_monitoring_platform/apps/notifications/tests/test_views.py
accessibility_monitoring_platform/apps/notifications/views.py

Trello card [#1897](https://trello.com/c/hPlTSvND/1897-remove-page-redirect-on-reminders-page).

1897: Redirect to create reminder on reminder delete

---

accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/exports/csv_export_utils.py
accessibility_monitoring_platform/apps/exports/tests/test_csv_export_utils.py
accessibility_monitoring_platform/apps/exports/tests/test_views.py

Trello card [#1899](https://trello.com/c/j1zBi0Gk/1899-update-all-csv-export-to-use-streaming).

1899: Turn all CSV exports into streaming downloads

---

accessibility_monitoring_platform/apps/common/templates/common/emails/backup/2a-sending-report-email-via-platform.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/2c-sending-report-email-public-complaint.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/4-12-week-update-request.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/4-seven-day-chaser-email-after-12-week-request.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/4b-12-week-update-new-site.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/6a-final-decision-generic.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/6b-final-decision-complaint-case.html
accessibility_monitoring_platform/apps/common/templates/common/emails/backup/6c-final-decision-no-contact-to-report-at-12-weeks.html

Trello card [#1903](https://trello.com/c/EXAdQ07M/1903-backup-email-templates).

1903: Backup email templates

---

.github/workflows/deploy-to-prod.yml
.github/workflows/deploy-to-test.yml
.github/workflows/tests.yml

Trello card [#1901](https://trello.com/c/6SvtbmBq/1901-update-ubuntu-version-on-copilot).

1901: Update Ubuntu version of GitHub workflows to 24.04

---

accessibility_monitoring_platform/apps/exports/csv_export_utils.py

Trello card [#1906](https://trello.com/c/fPwSOHCC/1906-csv-exports-using-wrong-case-number).

1906: Export Case.case_number instead of Case.id

---

accessibility_monitoring_platform/apps/cases/templates/cases/forms/case_close.html

Trello card [#1905](https://trello.com/c/L19UXwgt/1905-add-email-templates-to-closing-the-case-page).

1905: Add links to email templates to Closing the case page

---

package-lock.json
package.json

Trello card [#1907](https://trello.com/c/UklhPbBN/1907-upgrade-gds-design-system-to-v59).

1907: Upgrade govuk-frontend to version 5.9.0

---

accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/tests/test_models.py
accessibility_monitoring_platform/apps/notifications/tests/test_utils.py
accessibility_monitoring_platform/apps/notifications/utils.py

Trello card [#1900](https://trello.com/c/lmkPjTHZ/1900-fix-overdue-bug).

1900: Replace check of Case contact details found

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#1911](https://trello.com/c/AxErjJJk/1911-add-additional-search-options).

1911: Add recommendation for enforcement to Cases search

---

accessibility_monitoring_platform/apps/common/templates/common/emails/backup/6a-final-decision-generic.html
package-lock.json
requirements.txt
stack_tests/integration_tests/cypress/package-lock.json

Trello card [#1921](https://trello.com/c/pQwI9w2E/1921-upgrade-platform-dependencies).

1921: Upgrade dependencies

---

accessibility_monitoring_platform/apps/exports/csv_export_utils.py
accessibility_monitoring_platform/apps/exports/tests/test_csv_export_utils.py

Trello card [#1885](https://trello.com/c/sRU9HYV2/1885-add-final-statement-decision-to-survey-csv-export).

1885: Add final statement decision to feedback survey CSV

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/page_checks.html
accessibility_monitoring_platform/apps/audits/templates/audits/forms/twelve_week_retest_page_checks.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py

Trello card [#1918](https://trello.com/c/CHayNi4n/1918-include-ids-in-test-ui-text-filter).

1918: Filter WCAG check results by issue identifier

---

common/templates/reports_common/accessibility_report_container.html

Trello card [#1914](https://trello.com/c/W9lwuMzB/1914-full-width-report).

1914: Make accessibility monitoring report full width

---

requirements.in
requirements.txt

Trello card [#1930](https://trello.com/c/y9FOhQDO/1930-upgrade-django-to-518).

1930: Upgrade Django to version 5.1.8

---

accessibility_monitoring_platform/apps/common/sitemap.py
accessibility_monitoring_platform/apps/exports/templates/exports/export_case_as_email.html
accessibility_monitoring_platform/apps/exports/templates/exports/export_detail.html
accessibility_monitoring_platform/apps/exports/tests/test_views.py
accessibility_monitoring_platform/apps/exports/urls.py
accessibility_monitoring_platform/apps/exports/views.py

Trello card [#1931](https://trello.com/c/UlFdIanm/1931-ecni-export-as-emails).

1931: Add option to equality body export individual ECNI Case as an email

---

accessibility_monitoring_platform/apps/common/migrations/0006_remove_emailtemplate_slug_and_more.py
accessibility_monitoring_platform/apps/common/migrations/0007_populate_template_name.py

Trello card [#1932](https://trello.com/c/9yYYk3HT/1932-remove-email-templates-from-database).

1932: Fix migrations

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/pages.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/audits/views/initial.py

Trello card [#1939](https://trello.com/c/qDWTiTDT/1939-remove-hard-coded-standard-page-headers).

1939: Remove standard page headers

---

accessibility_monitoring_platform/apps/common/templates/common/emails/templates/9-our-audit-mentioned.html

Trello card [#1947](https://trello.com/c/bPxlvrTE/1947-create-email-template).

1947: Add email template 9.

---

__tests__/copy_text_to_clipboard.spec.js
accessibility_monitoring_platform/apps/audits/templates/audits/helpers/issue_identifier.html
accessibility_monitoring_platform/apps/common/templates/common/copy_text_to_clipboard.html
accessibility_monitoring_platform/apps/common/templates/common/icons/copy.svgt
accessibility_monitoring_platform/templates/base.html
common/static/js/copy_text_to_clipboard.js
common/static/scss/_global.scss
stack_tests/integration_tests/fixtures/audits.json
stack_tests/integration_tests/fixtures/statementcheck.json
stack_tests/integration_tests/fixtures/statementcheckresult.json

Trello card [#1954](https://trello.com/c/5xQAVJUp/1954-add-copy-option-for-wcag-id-in-test-summary).

1954: Add widget to copy text to clipboard

---

accessibility_monitoring_platform/apps/audits/forms.py

Trello card [#1916](https://trello.com/c/wgfPJ1RG/1916-add-js-widget-to-copy-a-check-mark-in-12-week-test).

1916: Add option to copy tick (✓) to clipboard

---

package-lock.json
requirements.in
requirements.txt
stack_tests/integration_tests/cypress/package-lock.json

Trello card [#1956](https://trello.com/c/YPbUN6es/1956-upgrade-dependencies-dependabot).

1956: dependabot says to upgrade dependencies

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/templates/cases/forms/create.html

Trello card [#1962](https://trello.com/c/wnFDvt44/1962-add-case-notes-to-create-case-page).

1962: Add notes field to Create case page

---

accessibility_monitoring_platform/apps/common/templates/common/emails/templates/7a-equality-body-retest-all-issues.html
accessibility_monitoring_platform/apps/common/templates/common/emails/templates/7b-equality-body-retest-unfixed-issues.html

Trello card [#1969](https://trello.com/c/NeAx95ow/1969-update-email-template-7b).

1969: Amend email tempate 7b

---

accessibility_monitoring_platform/apps/audits/models.py

Trello card [#1973](https://trello.com/c/U8FXleHX/1973-sort-failed-check-results-by-page).

1973: Sort failed check results by page

---

package-lock.json
requirements.txt
stack_tests/integration_tests/cypress/package-lock.json

Trello card [#1975](https://trello.com/c/42ZxvVlD/1975-upgrade-django-to-521).

1975: Upgrade Django to version `5.2.1`

---

accessibility_monitoring_platform/apps/common/templates/common/tech_team/ref_contents.html

Trello card [#1957](https://trello.com/c/cEhcw7VL/1957-store-event-history-by-case).

1957: Fix example Case history link on test platform

---

accessibility_monitoring_platform/apps/common/templates/common/tech_team/ref_contents.html

Trello card [#1957](https://trello.com/c/cEhcw7VL/1957-store-event-history-by-case).

1957: Add link to issue reports admin

---

accessibility_monitoring_platform/apps/audits/tests/test_views.py
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/case_nav.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/case_nav_group_pages.html
accessibility_monitoring_platform/apps/cases/templates/cases/helpers/case_nav_url.html
accessibility_monitoring_platform/apps/cases/tests/test_views.py
common/static/scss/_global.scss

1968: Removed underline from case nav and added blue boarder to current section

---

accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/tests/test_models.py

Trello card [#1957](https://trello.com/c/cEhcw7VL/1957-store-event-history-by-case).

1957: Add defensive code and tests

---

accessibility_monitoring_platform/apps/common/templates/common/tech_team/ref_contents.html
accessibility_monitoring_platform/apps/common/templates/common/tech_team/ref_gds_components.html
accessibility_monitoring_platform/apps/common/templates/common/tech_team/ref_headers.html
accessibility_monitoring_platform/apps/common/templates/common/tech_team/ref_widget_go_back.html
accessibility_monitoring_platform/apps/common/templates/common/tech_team/ref_widget_markdown.html
accessibility_monitoring_platform/apps/common/templates/common/tech_team/ref_widgets.html
accessibility_monitoring_platform/apps/common/templates/common/tech_team/reference_implementation.html

Trello card [#1976](https://trello.com/c/3wI4Ybpm/1976-update-reference-implementations).

1976: Document go back widget on reference implementations page

---

accessibility_monitoring_platform/apps/audits/admin.py

Trello card [#2001](https://trello.com/c/vkVNKMAR/2001-update-statement-questions).

2001: Enable export of statement checks in Django admin

---

accessibility_monitoring_platform/apps/audits/utils.py
accessibility_monitoring_platform/apps/common/forms.py
accessibility_monitoring_platform/apps/common/sitemap.py
accessibility_monitoring_platform/apps/common/templates/common/tech_team/ref_contents.html
accessibility_monitoring_platform/apps/common/urls.py
accessibility_monitoring_platform/apps/common/views.py

Trello card [#2001](https://trello.com/c/vkVNKMAR/2001-update-statement-questions).

2001: Remove one-off bulk update of statement questions

---

accessibility_monitoring_platform/apps/exports/csv_export_utils.py
accessibility_monitoring_platform/apps/exports/tests/test_csv_export_utils.py

Trello card [#2005](https://trello.com/c/Wa736Ofe/2005-field-missing-from-csv).

2005: Add enforcement_body_closed_case to Export to CSV

---

accessibility_monitoring_platform/apps/exports/tests/test_views.py
accessibility_monitoring_platform/apps/exports/views.py

Trello card [#2012](https://trello.com/c/YpumrbLX/2012-recalculate-simplified-case-statuses-on-export).

2012: Recalculate SimplifiedCase statuses on export

---

accessibility_monitoring_platform/apps/cases/utils.py

Trello card [#2011](https://trello.com/c/Hvhfs3ZW/2011-case-number-search).

2011: Improve case number search

---

accessibility_monitoring_platform/apps/notifications/tests/test_utils.py
accessibility_monitoring_platform/apps/notifications/utils.py

Trello card [#2013](https://trello.com/c/sohUMK7Y/2013-4-week-followup-is-not-flagging-on-tasks).

2013: Hide overdue task when Case has pending unread reminder

---

accessibility_monitoring_platform/apps/simplified/templates/simplified/forms/case_close.html

Trello card [#1926](https://trello.com/c/H5G0bxzD/1926-change-wording-on-closing-the-case-page).

1926: Change wording on Closing the case page

---

common/templates/reports_common/accessibility_report_v1_8_0__20250424.html

Trello card [#1985](https://trello.com/c/ABs40lMU/1985-remove-to-fix-the-issues-from-report).

1985: Remove 'to fix the issues' from report

---

package-lock.json
requirements.txt
stack_tests/integration_tests/cypress/package-lock.json

Trello card [#2057](https://trello.com/c/Ek0ZwsAt/2057-upgrade-dependencies-dependabot).

2057: Update dependencies - dependabot

---

accessibility_monitoring_platform/apps/simplified/forms.py
package-lock.json
requirements.txt
stack_tests/integration_tests/cypress/package-lock.json

* Update dependencies - dependabot ([alerts](https://github.com/alphagov/accessibility-monitoring-platform/security/dependabot)) [#2057](https://trello.com/c/Ek0ZwsAt/2057-upgrade-dependencies-dependabot)

v0.7.22 - Update dependencies - dependabot

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/templates/cases/basecase_list.html
accessibility_monitoring_platform/apps/cases/tests/test_utils.py
accessibility_monitoring_platform/apps/cases/utils.py
accessibility_monitoring_platform/apps/cases/views.py

Trello card [#2056](https://trello.com/c/goOk3y3P/2056-include-case-number-in-advance-search).

2056: Add case number to advanced search

---

accessibility_monitoring_platform/apps/audits/utils.py
accessibility_monitoring_platform/apps/users/forms.py
package-lock.json
requirements.txt
stack_tests/integration_tests/cypress/package-lock.json

Trello card [#2065](https://trello.com/c/uCwOP6X8/2065-upgrade-django-to-526).

2065: Upgrade Django to 5.2.6

---

accessibility_monitoring_platform/apps/audits/templates/audits/forms/equality_body_retest_page_checks.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py

Trello card [#2066](https://trello.com/c/a3ljOcwM/2066-show-date-of-retest).

2066: Show dates of initial, 12-week and equality body retest notes

---

accessibility_monitoring_platform/apps/audits/templates/audits/helpers/test_summary_new_12_week_statement_content.html
accessibility_monitoring_platform/apps/audits/tests/test_views.py

Trello card [#2072](https://trello.com/c/9bEJK6ad/2072-custom-issue-text-missing).

2072: Show 12-week custom statement comment outstanding issue text

---

accessibility_monitoring_platform/apps/tech/utils.py

Trello card [#1974](https://trello.com/c/ztTuo9Cp/1974-add-the-process-to-create-detailed-and-mobile-cases-design-attached).

1974: Import more detailed case statuses

---

accessibility_monitoring_platform/apps/cases/forms.py
accessibility_monitoring_platform/apps/cases/models.py
accessibility_monitoring_platform/apps/cases/templates/cases/basecase_list.html
accessibility_monitoring_platform/apps/cases/tests/test_models.py
accessibility_monitoring_platform/apps/detailed/csv_export.py
accessibility_monitoring_platform/apps/detailed/models.py
accessibility_monitoring_platform/apps/detailed/tests/test_forms.py
accessibility_monitoring_platform/apps/detailed/tests/test_models.py
accessibility_monitoring_platform/apps/detailed/tests/test_utils.py
accessibility_monitoring_platform/apps/detailed/tests/test_views.py
accessibility_monitoring_platform/apps/detailed/urls.py
accessibility_monitoring_platform/apps/detailed/utils.py
accessibility_monitoring_platform/apps/detailed/views.py
accessibility_monitoring_platform/apps/simplified/csv_export.py
accessibility_monitoring_platform/apps/simplified/models.py
accessibility_monitoring_platform/apps/simplified/tests/test_forms.py
accessibility_monitoring_platform/apps/simplified/tests/test_models.py
accessibility_monitoring_platform/apps/simplified/tests/test_views.py

Trello card [#2081](https://trello.com/c/AfTWKvzI/2081-add-ehrc-csv-export-for-detailed).

2081: Add Export to equality body CSV for detailed cases

---

accessibility_monitoring_platform/apps/common/templates/common/case_form.html
accessibility_monitoring_platform/apps/detailed/templates/detailed/details/details_psb_zendesk_tickets.html
accessibility_monitoring_platform/apps/notifications/templates/notifications/task_list.html

Trello card [#2086](https://trello.com/c/DMkGgsvT/2086-task-reminder-case-link-wrong).

2086: Fix link to case for reminders on task list
