- .github/workflows/deploy-to-prod.yml
- .github/workflows/deploy-to-test.yml
- .github/workflows/tests.yml
- Makefile
- deploy_feature_to_paas/app/build_env.py
- stack_tests/django_app.Dockerfile
- stack_tests/report_viewer_app.Dockerfile
Trello card [#882](https://trello.com/c/kAJl5GKu/882-fix-devops-scripts-following-changes-to-pipenv).
> 882: Replace pipenv lock -r with pipenv requirements

- accessibility_monitoring_platform/apps/reports/tests/test_utils.py
- accessibility_monitoring_platform/apps/reports/utils.py
Trello card [#889](https://trello.com/c/30NMisfr/889-add-govuk-domains-to-links-to-published-reports).
> 889: Map .gov.uk domains from platform to viewer

- .github/workflows/deploy-to-prod.yml
- .github/workflows/deploy-to-test.yml
- deploy_feature_to_paas/app/build_env.py
Trello card [#899](https://trello.com/c/MAD3dWKZ/899-unable-to-deploy-broken-buildpack).
> 889: Use working cloudfoundry python-buildpack version 1.7.58

- .github/workflows/deploy-to-prod.yml
- .github/workflows/deploy-to-test.yml
- cf_manifest/manifest-prod.yml
- cf_manifest/manifest-test.yml
- deploy_feature_to_paas/app/build_env.py
- deploy_feature_to_paas/main.py
- deploy_feature_to_paas/manifest_template.txt
Trello card [#899](https://trello.com/c/MAD3dWKZ/899-unable-to-deploy-broken-buildpack).
> 889: Pin fixed python-buildpack version 1.7.58 in manifests

- cf_manifest/manifest-prod.yml
- cf_manifest/manifest-test.yml
- deploy_feature_to_paas/manifest_template.txt
Trello card [#902](https://trello.com/c/eeA0tYIc/902-revert-pythonbuildpack-version-pinning)
> 902: Stop pinning python_buildpack to specific version

- requirements.in
- requirements.txt
- requirements_for_test.txt
Trello card [#907](https://trello.com/c/wOC8Mwp7/907-stop-using-pipenv).
> 907: Add pytest to normal requirements - for smoke tests

- requirements.in
- requirements.txt
Trello card [#914](https://trello.com/c/jnziVory/914-upgrade-django-to-411).
> 914: Upgrade Django to version 4.1.1.

- common/templates/reports_common/accessibility_report_container.html
- common/templates/reports_common/accessibility_report_v1_0_0__20220406.html
Trello card [#917](https://trello.com/c/3rMoPlV8/917-add-role-to-nav-bar-element-in-report-viewer).
> 917: Name nav tags in report unique to screen readers.

- accessibility_monitoring_platform/apps/common/templates/common/phase_banner.html
- accessibility_monitoring_platform/apps/common/tests/test_views.py
Trello card [#927](https://trello.com/c/7u7ljW3S/927-report-issue-disabled-on-test).
> 927: Reenable issue report link in test platform.

- accessibility_monitoring_platform/apps/audits/templates/audits/forms/summary.html
- accessibility_monitoring_platform/apps/cases/templates/cases/details/reminders.html
- accessibility_monitoring_platform/apps/cases/templates/cases/details/report_correspondence.html
- accessibility_monitoring_platform/apps/cases/templates/cases/details/twelve_week_correspondence.html
- accessibility_monitoring_platform/apps/comments/templates/comment_row.html
- common/static/scss/_global.scss
Trello card [#921](https://trello.com/c/o5Ej0ZMO/921-run-note-fields-through-markdown).
> 921: Treat notes fields' content as markdown.

- accessibility_monitoring_platform/apps/cases/models.py
- accessibility_monitoring_platform/apps/overdue/tests.py
- accessibility_monitoring_platform/apps/overdue/utils.py
Trello card [#874](https://trello.com/c/IhTM41a6/874-report-correspondence-has-five-working-days-in-the-chaser-currently-it-is-five-cal-days).
> 874: Change correspondence overdue period from 5 days to 7.

- accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
Trello card [#932](https://trello.com/c/MULp9Vx8/932-change-view-report-link-in-search-results-to-redirect-to-the-report-publisher-page-and-not-the-edit-report-page).
> 932: Link to report publisher from case search results.

- accessibility_monitoring_platform/apps/cases/templates/cases/forms/qa_process.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/report_correspondence.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- accessibility_monitoring_platform/apps/reports/models.py
- accessibility_monitoring_platform/apps/reports/templates/reports/forms/metadata.html
- accessibility_monitoring_platform/apps/reports/templates/reports/forms/section.html
- accessibility_monitoring_platform/apps/reports/templates/reports/report_edit.html
- accessibility_monitoring_platform/apps/reports/templates/reports/report_publisher.html
- accessibility_monitoring_platform/apps/reports/templates/reports/report_visits_metrics.html
- accessibility_monitoring_platform/apps/reports/tests/test_views.py
- accessibility_monitoring_platform/apps/reports/urls.py
- accessibility_monitoring_platform/apps/reports/views.py
Trello card [#939](https://trello.com/c/FW5oNSY1/939-fix-edit-report-breadcrumbs).
> 939: Correct breadcrumbs in report UI.

- accessibility_monitoring_platform/apps/audits/templates/audits/helpers/no_psb_response_notification.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/report_correspondence.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/report_details.html
- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/compliant_website_notification.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- accessibility_monitoring_platform/apps/reports/templates/reports/helpers/awaiting_approval_notification.html
- accessibility_monitoring_platform/apps/reports/templates/reports/helpers/pending_published_rebuild_notification.html
- accessibility_monitoring_platform/apps/reports/templates/reports/helpers/pending_unpublished_rebuild_notification.html
- accessibility_monitoring_platform/apps/reports/templates/reports/helpers/qa_process_notification.html
- accessibility_monitoring_platform/apps/reports/templates/reports/helpers/s3_report_notification.html
- accessibility_monitoring_platform/apps/reports/templates/reports/report_confirm_publish.html
- stack_tests/integration_tests/test_1.py
Trello card [#946](https://trello.com/c/gAcKZrm4/946-make-link-labels-consistent).
> 946: Use breadcrumb-style labels for links to pages.

- accessibility_monitoring_platform/apps/audits/models.py
- accessibility_monitoring_platform/apps/audits/tests/test_models.py
- accessibility_monitoring_platform/apps/audits/views.py
Trello card [#950](https://trello.com/c/MSWWlFJj/950-move-pdf-in-testing-pages-to-the-bottom-of-the-list).
> 950: Put PDF page at end of lists in report and UI.

- accessibility_monitoring_platform/apps/audits/templates/audits/details/retest_statement.html
Trello card [#961](https://trello.com/c/YiBSKLQb/961-wcag-dont-render-empty-links).
> 961: Check URL exists before rendering link

- accessibility_monitoring_platform/apps/audits/tests/test_views.py
- accessibility_monitoring_platform/apps/audits/views.py
- accessibility_monitoring_platform/apps/reports/templates/reports/report_publisher.html
Trello card [#964](https://trello.com/c/akZ4y8ZN/964-change-save-and-exit-in-the-final-step-of-the-testing-ui-to-link-to-testing-details-instead-of-the-testing-overview).
> 964: Redirect to case on save and exit from testing UI

- accessibility_monitoring_platform/apps/dashboard/templates/dashboard/dashboard.html
- accessibility_monitoring_platform/apps/dashboard/tests/test_views.py
- accessibility_monitoring_platform/templates/navbar.html
Trello card [#957](https://trello.com/c/Azu8Z2ww/957-wcag-buttons-must-have-discernible-text).
> 957: Hide search icons from the accessibility api.

- stack_tests/integration_tests/cypress/e2e/audit.cy.js
Trello card [#998](https://trello.com/c/P8qfeTtz/998-remove-broken-test).
> 998: Remove broken redundant test.

- accessibility_monitoring_platform/apps/audits/models.py
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/contact_formset.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- accessibility_monitoring_platform/apps/cases/utils.py
Trello card [#984](https://trello.com/c/PciPxGwm/984-add-link-to-contact-page-and-statement-in-the-platforms-contact-page-design-attached).
> 984: Add links to contact and statement pages to contact UI.

- accessibility_monitoring_platform/apps/audits/templates/audits/helpers/accessibility_statement_link.html
- accessibility_monitoring_platform/apps/audits/tests/test_views.py
Trello card [#985](https://trello.com/c/ajwNqVkz/985-add-text-next-to-link-for-statement-saying-there-is-no-statement-in-test-ui).
> 985: Hide link to accessibility statement if none exists.

- accessibility_monitoring_platform/apps/cases/forms.py
Trello card [#1022](https://trello.com/c/nOpQKt52/1022-add-this-is-required-for-status-help-text-to-qa-auditor-on-the-qa-page).
> 1022: Add affects status help text to QA auditor field.

- accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_page_comparison.html
- accessibility_monitoring_platform/apps/audits/tests/test_views.py
- stack_tests/integration_tests/fixtures/audits.json
Trello card [#1020](https://trello.com/c/C2bMf1mI/1020-add-additional-issues-to-the-summary-page).
> 1020: Show page retest notes on comparison page.

- accessibility_monitoring_platform/apps/audits/models.py
- accessibility_monitoring_platform/apps/audits/templates/audits/details/retest_statement.html
- accessibility_monitoring_platform/apps/audits/templates/audits/details/statement.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_1.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_2.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/statement_1.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/statement_2.html
- accessibility_monitoring_platform/apps/audits/templates/audits/helpers/accessibility_statement_link.html
- accessibility_monitoring_platform/apps/audits/templates/audits/helpers/no_statement_warning.html
- accessibility_monitoring_platform/apps/audits/tests/test_models.py
- accessibility_monitoring_platform/apps/audits/tests/test_views.py
Trello card [#1021](https://trello.com/c/nNSjSgB3/1021-hide-statement-assessment-form-if-statement-doesnt-exist-design-attached).
> 1021: Hide accessibility statement details when no such page.

- accessibility_monitoring_platform/apps/common/chart.py
- accessibility_monitoring_platform/apps/common/tests/test_chart.py
One of the tests was using the current time by mistake. That test failed today when the month changed from November to December.
Trello card [#1034](https://trello.com/c/nMAtrj0t/1034-add-report-metrics).
> 1034: Patch test to use a mock time.

- common/static/scss/_global.scss
Trello card [#1043](https://trello.com/c/FlHtZ48p/1043-use-gds-transport-font-inside-svg-charts).
> 1043: Use GDS Transport font inside of SVG charts.

- accessibility_monitoring_platform/apps/cases/templates/cases/details/testing_details.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
Trello card [#1068](https://trello.com/c/C4V0u1ux/1068-missing-link-to-spreadsheet-test-results).
> 1068: Show link to test results only when URL is present.

- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_contents.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
Trello card [#1071](https://trello.com/c/zK3oB7Mi/1071-spreadsheet-testing-case-showing-platform-ui-in-contents).
> 1071: Hide link to 12-week retest when spreadsheet.

- accessibility_monitoring_platform/apps/cases/templates/cases/details/testing_details.html
- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/nav_contents.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
* Hide link to 12-week retest when spreadsheet testing. ([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/1/view/)) [#1071](https://trello.com/c/zK3oB7Mi/1071-spreadsheet-testing-case-showing-platform-ui-in-contents)
> v0.4.54 - Hide link to 12-week retest when spreadsheet testing.

- common/static/js/markdown_preview.js
Trello card [#1078](https://trello.com/c/0fT5gtLg/1078-code-blocks-wrong-in-previews).
> 1078: Fix codeblocks in showdownjs markdown previews.

- accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_pages.html
- accessibility_monitoring_platform/apps/audits/tests/test_views.py
Trello card [#1079](https://trello.com/c/x3lfoq5Y/1079-add-page-missing-label-to-12-week-retest-overview-page-design-attached).
> 1079: Remind user if page marked as missing on retest.

- __tests__/audits_check_filter.spec.js
- common/static/js/audits_check_filter.js
Trello card [#1116](https://trello.com/c/57xHlXef/1116-change-errors-to-error-on-testing-pages-when-there-is-one-error).
> 1116: Label errors as error when there is only one

- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- accessibility_monitoring_platform/apps/cases/views.py
- accessibility_monitoring_platform/apps/common/form_extract_utils.py
- accessibility_monitoring_platform/apps/common/tests/test_form_extract_utils.py
Trello card [#1137](https://trello.com/c/Q04zBUf9/1137-remove-link-to-odt-report-and-link-to-final-pdf-report-in-case-overview).
> 1137: Hide links to report files when platform reporting used

- accessibility_monitoring_platform/apps/cases/templates/cases/forms/qa_process.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- accessibility_monitoring_platform/apps/cases/views.py
Trello card [#1142](https://trello.com/c/ZjDAsNG5/1142-make-sure-add-comment-in-qa-page-saves-the-page).
> 1142: Save QA process form when Add comment button is pressed

- accessibility_monitoring_platform/apps/cases/tests/test_utils.py
- accessibility_monitoring_platform/apps/cases/utils.py
Trello card [#1165](https://trello.com/c/hvL5g908/1165-add-column-to-csv).
> 1165: Add Enforcement recommendation notes to Export to feedback survey CSV

- accessibility_monitoring_platform/apps/audits/forms.py
- accessibility_monitoring_platform/apps/audits/tests/test_views.py
- accessibility_monitoring_platform/apps/audits/views.py
Trello card [#1140](https://trello.com/c/qr6j1PFY/1140-have-two-pages-compulsory-on-the-add-pages-page-design-attached).
> 1140: Show fields to create two extra pages if none exist

- accessibility_monitoring_platform/apps/reports/tests/test_views.py
- accessibility_monitoring_platform/apps/reports/views.py
Trello card [#1155](https://trello.com/c/GMFdeDht/1155-views-and-unique-visitors-is-missing-in-report-editor).
> 1155: Fix displaying numbers of visitors on Edit report page

- accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
Trello card [#1167](https://trello.com/c/pYabsO8w/1167-add-percentages-to-case-overview-page-design-attached).
> 1167: Add percentages to outstanding issues page

- accessibility_monitoring_platform/apps/audits/forms.py
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_1.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_2.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_statement_decision.html
Trello card [#1100](https://trello.com/c/Vn95pWV8/1100-move-link-to-12-week-saved-accessibility-statement-only-if-not-compliant-field-to-statement-compliance-decision-page).
> 1100: Move 12-week statement backup field to compliance page

- accessibility_monitoring_platform/apps/cases/templates/cases/forms/contact_formset.html
Trello card [#1205](https://trello.com/c/tleBnjSL/1205-move-contact-notes-field).
> 1205: Move contact detail notes to bottom of page

- accessibility_monitoring_platform/apps/audits/models.py
- accessibility_monitoring_platform/apps/audits/tests/test_models.py
Trello card [#1190](https://trello.com/c/S3GtmYg1/1190-removed-pages-should-be-removed-from-the-final-stats-in-outstanding-issues-page).
> 1190: Remove pages missing on retest from outstanding issues

- accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
- accessibility_monitoring_platform/apps/cases/templates/cases/details/qa_process.html
- accessibility_monitoring_platform/apps/cases/templates/cases/details/report_details.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
Trello card [#1172](https://trello.com/c/Zmp8yqAb/1172-review-how-qa-case-overview-page-represents-links-to-the-report).
> 1172: Remove report links from QA section of View case page

- accessibility_monitoring_platform/apps/cases/forms.py
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
Trello card [#1227](https://trello.com/c/yVNSJmJ0/1227-re-add-preferred-contact-field-design-attached).
> 1227: Restore preferred contact UI

- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- accessibility_monitoring_platform/apps/cases/views.py
Trello card [#1226](https://trello.com/c/RkPYLMZB/1226-remove-auto-assign-qa-auditor-when-report-is-approved).
> 1226: Remove automatic update of QA auditor on report approval

- accessibility_monitoring_platform/apps/cases/templates/cases/forms/report_correspondence.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/twelve_week_correspondence.html
- accessibility_monitoring_platform/apps/cases/tests/test_utils.py
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- accessibility_monitoring_platform/apps/cases/utils.py
- accessibility_monitoring_platform/apps/cases/views.py
- accessibility_monitoring_platform/apps/common/templates/common/amp_field_two_column.html
Trello card [#1087](https://trello.com/c/wsyWhnfv/1087-combine-correspondence-due-dates-into-one-page).
> 1087: Move links to edit derived dates to be inline with page flow

- accessibility_monitoring_platform/apps/cases/tests/test_utils.py
- accessibility_monitoring_platform/apps/cases/utils.py
Trello card [#1102](https://trello.com/c/VPLY31KN/1102-add-psb-is-unrepsonsive-column-in-eb-csv-export).
> 1102: Add unresponsive column to equality body CSV

- common/static/scss/_global.scss
- report_viewer/apps/viewer/tests.py
- report_viewer/apps/viewer/utils.py
- report_viewer/apps/viewer/views.py
- report_viewer/templates/base.html
Trello card [#1235](https://trello.com/c/F0wbcWqO/1235-add-banner-to-warn-public-orgs-about-the-site-going-down-during-cloud-migration-design-attached).
> 1235: Add banner to report warning of outage 10-14 July 2023

- accessibility_monitoring_platform/apps/reports/templates/reports/report_publisher.html
- accessibility_monitoring_platform/apps/reports/tests/test_views.py
Trello card [#1245](https://trello.com/c/9kkArby4/1245-redesign-headline-buttons-in-report-publisher-design-attached).
> 1245: Change button labels on Report publisher page

- accessibility_monitoring_platform/apps/audits/tests/test_views.py
- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/overview.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- accessibility_monitoring_platform/apps/common/templates/common/frequently_used_links.html
Trello card [#1247](https://trello.com/c/LVldHokh/1247-make-it-easier-to-get-to-the-published-report-design-attached).
> 1247: Add another link to the latest HTML report

- accessibility_monitoring_platform/apps/reports/templates/reports/helpers/nav_contents.html
- accessibility_monitoring_platform/apps/reports/tests/test_views.py
Trello card [#1265](https://trello.com/c/3uYh2vVB/1265-report-options-still-in-report-wrapper).
> 1265: Show/hide links to Report options/Statement overview in Report publisher

- package-lock.json
- package.json
Trello card [#1277](https://trello.com/c/Pm03I2lR/1277-upgrade-gds-design-system-to-470).
> 1277: Upgrade GDS design system to 4.7.0.

- .github/workflows/platform-checking.yml
- check_headers.py
- check_platforms.py
- stack_tests/integration_tests/cypress/e2e/production_test.cy.js
- stack_tests/smoke_tests/cypress/e2e/headers.cy.js
Trelo card [#1337](https://trello.com/c/KdLAPdzG/1337-research-whether-we-can-do-some-basic-security-tests-during-deployment-tests).
> 1337: Add check of response headers to smoke tests

- accessibility_monitoring_platform/apps/cases/templates/cases/details/report_details.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/qa_process.html
- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/overview.html
- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/status_requirements.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- accessibility_monitoring_platform/apps/common/templates/common/frequently_used_links.html
- accessibility_monitoring_platform/apps/reports/templates/reports/helpers/overview.html
- accessibility_monitoring_platform/apps/reports/templates/reports/helpers/overview_status.html
- accessibility_monitoring_platform/apps/reports/templates/reports/report_publisher.html
- accessibility_monitoring_platform/apps/reports/tests/test_views.py
- stack_tests/integration_tests/cypress/e2e/new_case_test_report.cy.js
- stack_tests/integration_tests/cypress/e2e/report.cy.js
Trello card [#1334](https://trello.com/c/cwaUdVSN/1334-add-published-time-and-version-number-to-report-overview-design-attached) and [#1257](https://trello.com/c/PiylNn7t/1257-change-final-report-to-published-report-in-the-platform).
> 1334: Show published report version and date

- accessibility_monitoring_platform/apps/cases/templates/cases/details/contact_details.html
- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/report_link_draft.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
Trello card [#1360](https://trello.com/c/ndWxfyNg/1360-sanitise-pii-from-prototype-data-backup).
> 1360: Fix link to report preview; Remove Contact notes

- accessibility_monitoring_platform/settings/base.py
- accessibility_monitoring_platform/settings/deploy.py
- aws_prototype/main.py
- aws_prototype/tests/test_utils.py
- aws_prototype/utils.py
- report_viewer/settings/base.py
- report_viewer/settings/deploy.py
Trello cards:
* [#1378](https://trello.com/c/6KWdtLEn/1378-fix-links-to-published-report-in-prototypes) Fix links to published reports in prototypes
* [#1372](https://trello.com/c/kjusICTS/1372-add-local-email-server-to-prototypes) Use console email backend in prototypes.
* [#1377](https://trello.com/c/pcoYpa20/1377-make-prototype-temporary-passwords-longer) Make temporary passwords longer in prototypes.
> 1378: Fix links to published reports in prototypes

- accessibility_monitoring_platform/apps/audits/templates/audits/audit_retest_detail.html
- accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_nav_contents.html
- accessibility_monitoring_platform/apps/audits/templates/audits/helpers/retest_nav_steps.html
- accessibility_monitoring_platform/apps/audits/tests/test_views.py
- accessibility_monitoring_platform/apps/cases/templates/cases/details/retesting_details.html
Trello card [#1374](https://trello.com/c/TGXqjm8U/1374-statement-comparison-missing-when-statement-is-added-at-12-week-retest-design-attached).
> 1374: Show statement comparison and compliance decision

- accessibility_monitoring_platform/apps/cases/forms.py
- accessibility_monitoring_platform/apps/cases/models.py
- accessibility_monitoring_platform/apps/cases/templates/cases/details/report_correspondence.html
- accessibility_monitoring_platform/apps/overdue/tests.py
- stack_tests/integration_tests/cypress/e2e/case.cy.js
Trello card [#1388](https://trello.com/c/Dg0MEJkp/1388-make-labels-clearer-in-the-correspondence-page).
> 1388: Add 'to report' to followup labels

- accessibility_monitoring_platform/apps/cases/templates/cases/emails/outstanding_issues.html
- accessibility_monitoring_platform/apps/cases/templates/cases/emails/twelve_week_correspondence.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
Trello card [#1293](https://trello.com/c/wsHrblAT/1293-include-no-wcag-errors-found-on-the-website-in-the-email-templates-when-there-are-no-errors-found).
> 1293: Add placeholder text to email templates when no WCAG issues

- accessibility_monitoring_platform/apps/audits/admin.py
- accessibility_monitoring_platform/apps/common/metrics.py
- accessibility_monitoring_platform/apps/common/tests/test_metrics.py
Trello card [#1416](https://trello.com/c/hXkjL4V2/1416-remove-initial-wcag-issues-from-stats-when-the-page-is-missing-in-the-12-week-retest).
> 1416: Exclude missing pages from policy metrics

- accessibility_monitoring_platform/apps/reports/templates/reports/report_publisher.html
Trello card [#1418](https://trello.com/c/8JTG7B84/1418-make-the-view-report-button-green-and-the-republish-report-button-grey).
> 1418: Swap button colours on Report publisher page

- accessibility_monitoring_platform/apps/cases/forms.py
- accessibility_monitoring_platform/apps/cases/models.py
- accessibility_monitoring_platform/apps/cases/templates/cases/case_list.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/create.html
- accessibility_monitoring_platform/apps/cases/tests/test_utils.py
- accessibility_monitoring_platform/apps/cases/utils.py
- accessibility_monitoring_platform/apps/common/models.py
- amp_platform.DockerFile
* Use new case details fields; Show website name all over the UI ([example](https://platform.accessibility-monitoring.service.gov.uk/reports/370/report-publisher/)) [#1452](https://trello.com/c/2eCxFDGd/1452-use-new-case-details-fields)
> v0.6.27 - Use new case details fields; Show website name all over the UI

- accessibility_monitoring_platform/apps/audits/forms.py
- accessibility_monitoring_platform/apps/audits/models.py
- accessibility_monitoring_platform/apps/audits/tests/test_forms.py
Trello card [#1469](https://trello.com/c/Fy6KXD5U/1469-remove-the-option-to-add-statement-issues-to-statement-overview).
> 1469: Remove statement overview from statement section choices

- accessibility_monitoring_platform/apps/cases/templates/cases/forms/qa_process.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- accessibility_monitoring_platform/apps/cases/views.py
- accessibility_monitoring_platform/apps/dashboard/tests/test_utils.py
* Replace Add comment button with link ([example](https://platform.accessibility-monitoring.service.gov.uk/cases/1170/edit-qa-process/)) [#1471](https://trello.com/c/j0gqVGln/1471-case-changed-since-this-page-loaded-error)
> v0.6.35 - Replace Add comment button with link

- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/retest_statement_overview.html
- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/statement_overview.html
- accessibility_monitoring_platform/apps/audits/tests/test_views.py
Trello card [#1483](https://trello.com/c/V9Q4p8MM/1483-remove-obsolete-warning).
> 1483: Remove no-initial-statement warning from statement overview page

- accessibility_monitoring_platform/apps/audits/views/twelve_week.py
- accessibility_monitoring_platform/apps/cases/templates/cases/emails/outstanding_issues.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
Trello card [#1481](https://trello.com/c/VnbH6Uml/1482-oustanding-issues-email-shows-no-statement-issues-regardless-whether-issues-were-found-design-attached).
> 1482: Add 12-week statement check results to outstanding issues email

- accessibility_monitoring_platform/templates/base.html
- common/static/scss/_global.scss
- report_viewer/templates/base.html
Trello card [#1510](https://trello.com/c/4NqniQI3/1510-restore-pre-gds-design-system-500-headers).
> 1510: Override govuk header font size and weight

- accessibility_monitoring_platform/apps/cases/models.py
- accessibility_monitoring_platform/apps/cases/tests/test_models.py
- accessibility_monitoring_platform/apps/overdue/templates/overdue/overdue_list.html
- accessibility_monitoring_platform/apps/overdue/tests.py
- accessibility_monitoring_platform/apps/overdue/utils.py
Trello card [#1428](https://trello.com/c/KB1GWLJw/1428-add-7-day-overdue-notification-for-seven-day-no-contact-details-email-sent-report-correspondence).
> 1428: Show case overdue if report is ready to send and seven day no contact email sent date is more than seven days ago

- accessibility_monitoring_platform/apps/cases/templates/cases/forms/equality_body_correspondence_list.html
Trello card [#1519](https://trello.com/c/X779YIcT/1519-correct-spelling-mistake-in-zendesk-correspondence-mgmt-nessage-should-be-message).
> 1519: Correct spelling of nessage

- accessibility_monitoring_platform/apps/cases/forms.py
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/four_week_followup.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/one_week_followup.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/one_week_followup_final.html
- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/final_request_acknowledged_warning.html
- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/report_acknowledged_warning.html
- accessibility_monitoring_platform/apps/cases/tests/test_forms.py
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
Trello card [#1535](https://trello.com/c/hDiiKfAc/1535-add-notification-in-correspondence-pages-when-the-org-responds-to-the-report-and-update-request).
> 1535: Add warnings to correspondence UI

- accessibility_monitoring_platform/apps/cases/templates/cases/forms/case_close.html
Trello card [#1538](https://trello.com/c/8H7W6ve5/1538-add-email-sent-to-field-in-compliance-decision).
> 1538: Add contact details to email field on Closing the case page

- accessibility_monitoring_platform/apps/audits/templates/audits/helpers/statement_pages.html
Trello card [#1540](https://trello.com/c/DnNbXpF3/1540-have-statement-links-closed-by-default-in-the-statement-assessment).
> 1540: Close statement links' details elements by default

- accessibility_monitoring_platform/apps/cases/templates/cases/forms/contact_formset.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/find_contact_details.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/four_week_followup.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/one_week_followup.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/report_acknowledged.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/report_sent_on.html
- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/no_response_link.html
Trello card [#1547](https://trello.com/c/UIJxZ6Oc/1547-add-unable-to-send-report-or-no-response-from-public-sector-body-to-the-other-correspondence-pages).
> 1547: Add links to no-response page

- accessibility_monitoring_platform/apps/audits/models.py
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/twelve_week_retest_page_checks.html
- accessibility_monitoring_platform/apps/audits/tests/test_models.py
- accessibility_monitoring_platform/apps/audits/views/twelve_week.py
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/case_close.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- common/static/scss/_global.scss
- requirements.in
- requirements.txt
Trello card [#1433](https://trello.com/c/MEeQxGvd/1433-add-option-to-add-multipage-errors-in-12-week-test-like-how-its-done-in-the-initial-test-design-attached).
> 1433: Copy matching error notes in 12-week retest

- accessibility_monitoring_platform/apps/common/templates/common/phase_banner.html
- accessibility_monitoring_platform/templates/navbar.html
- common/static/scss/_global.scss
Trello card [#1608](https://trello.com/c/fRqdCOMt/1608-prevent-access-to-the-report-an-issue-page-or-forward-on-the-login-page).
> 1608: Suppress page_url when user is not logged in. May be upsetting security checking

- package-lock.json
- package.json
Trello card [#1612](https://trello.com/c/9a9om3hN/1612-upgrade-gds-design-system-to-v53).
> 1612: Upgrade GDS Design System to v5.3.0

- accessibility_monitoring_platform/settings/base.py
- accessibility_monitoring_platform/settings/deploy.py
- accessibility_monitoring_platform/templates/500.html
- accessibility_monitoring_platform/templates/base.html
- common/templates/reports_common/accessibility_report_container.html
- report_viewer/settings/base.py
- report_viewer/settings/deploy.py
- report_viewer/templates/base.html
Trello card [#1609](https://trello.com/c/TcD8c6YJ/1609-remove-os-from-the-codebase).
> 1609: Remove deprecated uses of os.path and os.system from platform

- report_viewer/apps/viewer/urls.py
Trello card [#1626](https://trello.com/c/bt9haqjc/1626-have-django-accept-urls-ending-with-a-forward-slash).
> 1626: Enable URLs ending in '/' in report viewer

- accessibility_monitoring_platform/apps/cases/models.py
- accessibility_monitoring_platform/apps/cases/tests/test_utils.py
- accessibility_monitoring_platform/apps/cases/utils.py
Trello card [#1663](https://trello.com/c/Z73ZlNri/1663-use-case-number-in-title-and-search).
> 1663: Search for Cases by `case_number` instead of `id`

- accessibility_monitoring_platform/apps/cases/templates/cases/emails/equality_body_retest_email.html
Trello card [#1659](https://trello.com/c/KGGSMlgK/1659-remove-errors-from-tally-if-page-is-missing-during-ehrc-retest).
> 1659: Hide error counts if page has been removed

- common/static/scss/init.scss
- package-lock.json
- package.json
Trello card [#1667](https://trello.com/c/wTQ9LFC4/1667-upgrade-govuk-frontend-to-540).
> 1667: Upgrade GovUK Frontend to version 5.4.0

- common/static/scss/_global.scss
Trello card [#1678](https://trello.com/c/BR2SMhMV/1678-add-red-non-bold-style-for-email-templates).
> 1678: Add red text for email templates

- accessibility_monitoring_platform/apps/reports/tests/test_views.py
- accessibility_monitoring_platform/apps/reports/views.py
- common/static/scss/_global.scss
* Restrict unique report visits to current case ([example](https://platform.accessibility-monitoring.service.gov.uk/reports/370/report-metrics-view/?showing=unique-visitors)) [#1684](https://trello.com/c/NPQCgwor/1684-filter-unique-report-visits-by-report)
> v0.6.83 - Restrict unique report visits to current case

- accessibility_monitoring_platform/apps/dashboard/templates/dashboard/6_report_ready_to_send.html
- accessibility_monitoring_platform/apps/dashboard/tests/test_views.py
Trello card [#1666](https://trello.com/c/8yQb75TW/1666-represent-no-contact-details-in-the-dashboard-home-page).
> 1666: Show when no contact details request sent on home page

- accessibility_monitoring_platform/apps/common/tests/test_utils.py
- accessibility_monitoring_platform/apps/common/utils.py
Trello card [#1703](https://trello.com/c/tDRijlXn/1703-make-http-prefixes-optional-in-bulk-url-searches).
> 1703: Make `http` protocol prefixes optional in bulk URL search

- accessibility_monitoring_platform/apps/cases/forms.py
TRello card [#1698](https://trello.com/c/ObZQ9c4G/1698-remove-included-in-equality-body-export-from-if-the-organisation-did-not-respond-to-the-12-week-update-request-field).
> 1698: Relabel organisation_response

- accessibility_monitoring_platform/apps/common/tests/test_utils.py
- accessibility_monitoring_platform/apps/common/utils.py
Trello card [#1703](https://trello.com/c/tDRijlXn/1703-make-http-prefixes-optional-in-bulk-url-searches).
> 1703: Add .net to global URL search preprocessing

- accessibility_monitoring_platform/apps/audits/templates/audits/helpers/twelve_week_retest_nav_steps.html
- accessibility_monitoring_platform/apps/audits/tests/test_views.py
- accessibility_monitoring_platform/apps/audits/views/twelve_week.py
Trello card [#1700](https://trello.com/c/VT1hp2oo/1700-there-are-no-overview-questions-during-the-12-week-statement-test-if-there-wasnt-a-statement-initially-this-is-clearly-a-bug-and).
> 1700: Show 12-week statement checks even if no statement initially existed

- accessibility_monitoring_platform/templates/base.html
- accessibility_monitoring_platform/templates/navbar.html
- common/static/scss/_global.scss
- report_viewer/templates/footer.html
Trello card [#1712](https://trello.com/c/Z9zzYBfi/1712-remove-30px-padding-when-window-size-goes-below-1020px-width).
> 1712: Remove padding and margins when window has small width

- accessibility_monitoring_platform/templates/500.html
Trello card [#1759](https://trello.com/c/YlvQBX6N/1759-fix-500html).
> 1759: Fix wrong asset names in 500.html

- accessibility_monitoring_platform/apps/cases/tests/test_views.py
- accessibility_monitoring_platform/apps/cases/views.py
Trello card [#1760](https://trello.com/c/z8FS63tq/1760-fix-equality-body-metadata-save-continue).
> 1760: Equality body metadata page always Save and continues to Equality body cores

- package-lock.json
- package.json
Trello card [#1773](https://trello.com/c/VstMVv5E/1773-upgrade-gds-design-system-to-v56).
> 1773: Upgrade GDS Design System to 5.6.0

- accessibility_monitoring_platform/apps/dashboard/templates/dashboard/list_view.html
Trello card [#1776](https://trello.com/c/muB4F4s4/1776-fix-aria-errors-on-open-accordion).
> 1776: Adjust accordion content ids to match convention expected by GDS Design System

- __tests__/url_field_dynamic_link.spec.js
- accessibility_monitoring_platform/apps/common/sitemap.py
- accessibility_monitoring_platform/apps/common/templates/common/amp_url_field_dynamic_link.html
- common/static/js/url_field_dynamic_link.js
- common/static/scss/_global.scss
Trello card [#1778](https://trello.com/c/NHGvf4ie/1778-dynamic-link-not-a-hyperlink).
> 1778: Open link placeholder replaced with hyperlink when URL entered

- accessibility_monitoring_platform/apps/cases/templates/cases/forms/equality_body_correspondence_list.html
- accessibility_monitoring_platform/apps/cases/tests/test_views.py
Trello card [#1715](https://trello.com/c/oPctTcUn/1715-add-continue-page-button-in-ehrc-zendesk-tickets).
> 1715: Add navigation links to Equality body correspondence page

- accessibility_monitoring_platform/apps/audits/tests/test_views.py
- accessibility_monitoring_platform/apps/audits/utils.py
Trello card [#1793](https://trello.com/c/cG2IQIYQ/1793-page-with-no-issues-shown-in-12-week-retest).
> 1793: Only show PSB pages with errors in 12-week UI

- accessibility_monitoring_platform/apps/audits/templates/audits/forms/twelve_week_retest_page_checks.html
- accessibility_monitoring_platform/apps/audits/tests/test_utils.py
- accessibility_monitoring_platform/apps/audits/utils.py
- accessibility_monitoring_platform/apps/audits/views/twelve_week.py
Trello card [#1792](https://trello.com/c/KVcZ3bQ7/1792-matching-errors-link-for-additional-issues-found-on-page).
> 1792: Show other pages' retest notes for copying

- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/overview_status.html
- accessibility_monitoring_platform/apps/cases/tests/test_models_status.py
Trello card [#1767](https://trello.com/c/kRuLl1R9/1767-ensure-the-links-route-correctly-in-the-task-page-and-status-links).
> 1767: Update links for report and 12-week correspondence in Case overview status

- accessibility_monitoring_platform/apps/audits/models.py
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/equality_body_retest_page_checks.html
- accessibility_monitoring_platform/apps/audits/tests/test_models.py
Trello card [#1716](https://trello.com/c/xOOFfHjk/1716-add-similar-errors-text-to-ehrc-retests).
> 1716: Add matching errors to equality body retest UI

- accessibility_monitoring_platform/apps/cases/forms.py
- stack_tests/smoke_tests/cypress/e2e/case.cy.js
* Swap order of fields on **Edit PSB Zendesk ticket** page ([example](https://platform.accessibility-monitoring.service.gov.uk/cases/3503/update-zendesk-ticket/)) [#1798](https://trello.com/c/Dg7w2NqX/1798-change-field-order-on-edit-psb-zendesk-ticket-page)
> v0.6.124 - Swap order of fields on **Edit PSB Zendesk ticket** page

- accessibility_monitoring_platform/apps/audits/templates/audits/forms/retest_test_summary.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/test_summary.html
- accessibility_monitoring_platform/apps/audits/tests/test_views.py
- accessibility_monitoring_platform/apps/audits/views/initial.py
- accessibility_monitoring_platform/apps/audits/views/twelve_week.py
Trello card [#1816](https://trello.com/c/GgQKTaQ8/1816-add-hide-fixed-to-test-summary-pages).
> 1816: Restore hide fixed button to 12-week retest summary pages

- accessibility_monitoring_platform/apps/cases/templates/cases/helpers/overview.html
Trello card [#1813](https://trello.com/b/7qRdnJ8t/building-tools-to-facilitate-manual-testing).
> 1813: Don't use default overdue link on View case page

- accessibility_monitoring_platform/apps/audits/templates/audits/forms/twelve_week_pages.html
- accessibility_monitoring_platform/apps/common/sitemap.py
- accessibility_monitoring_platform/apps/common/tests/test_sitemap.py
Trello card [#1829](https://trello.com/c/tZpEUKB8/1829-empty-12-week-retest-causes-500-error-after-pressing-save-and-continue).
> 1829: Hide pages with no initial errors from retest UI

- accessibility_monitoring_platform/apps/audits/templates/audits/forms/page_checks.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/twelve_week_retest_page_checks.html
- accessibility_monitoring_platform/apps/audits/tests/test_views.py
Trello card [#1861](https://trello.com/c/ZyGhCXT2/1861-restore-missing-back-to-top-link).
> 1861: Restore back to top link removed in error

- accessibility_monitoring_platform/apps/audits/templates/audits/forms/equality_body_retest_page_checks.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/equality_body_retest_statement_pages_formset.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/page_checks.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/pages.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/statement_pages_formset.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/twelve_week_retest_page_checks.html
- accessibility_monitoring_platform/apps/audits/templates/audits/forms/twelve_week_statement_pages_formset.html
- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_compliance.html
- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_custom.html
- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_feedback.html
- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_non_accessible.html
- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_overview.html
- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_preparation.html
- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/equality_body_retest_statement_website.html
- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/retest_statement_formset_form.html
- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/retest_statement_other.html
- accessibility_monitoring_platform/apps/audits/templates/audits/statement_checks/statement_formset_form.html
- accessibility_monitoring_platform/apps/cases/templates/cases/forms/contact_create.html
- accessibility_monitoring_platform/apps/cases/templates/cases/outstanding_issues.html
- accessibility_monitoring_platform/apps/cases/templates/cases/status_workflow.html
- accessibility_monitoring_platform/apps/common/templates/common/contact_admin.html
- accessibility_monitoring_platform/apps/common/templates/common/error_summary.html
- accessibility_monitoring_platform/apps/common/templates/common/formset_error_summary.html
- accessibility_monitoring_platform/apps/common/templates/common/issue_report.html
- accessibility_monitoring_platform/apps/common/templates/common/platform_checking.html
- accessibility_monitoring_platform/apps/common/templates/common/settings/edit_footer_links.html
- accessibility_monitoring_platform/apps/common/templates/common/settings/edit_frequently_used_links.html
- accessibility_monitoring_platform/apps/notifications/templates/notifications/reminder_task_create.html
- accessibility_monitoring_platform/apps/notifications/templates/notifications/reminder_task_update.html
Trello card [#1869](https://trello.com/c/mjilj7cN/1869-suppress-multiple-error-messages-in-form-sets).
> 1869: Show error summary only once for each form with errors

- accessibility_monitoring_platform/templates/footer.html
Trello card [#1904](https://trello.com/c/Wt7qBhXO/1904-add-external-links-to-the-footer).
> 1904: Remove (nested) redundant check if user is logged in

- accessibility_monitoring_platform/settings/base.py
Trello card [#1880](https://trello.com/c/gwpOkmI1/1880-axe-login-manager-is-recording-the-post-attempt-in-plain-text).
> 1880: Mask auth-password content in django-axes records

- accessibility_monitoring_platform/settings/base.py
- amp_platform.DockerFile
Trello card [#1880](https://trello.com/c/gwpOkmI1/1880-axe-login-manager-is-recording-the-post-attempt-in-plain-text).
> 1880: Delete django-axes access attempts and logs over 7 days old

- common/static/scss/_global.scss
Trello card [#1936](https://trello.com/c/fndlUBKP/1936-bump-up-padding-in-report-tables-from-10px-to-15px).
> 1936: Increase padding in report tables.

- accessibility_monitoring_platform/apps/common/templates/common/emails/templates/4-12-week-update-request.html
- accessibility_monitoring_platform/apps/common/templates/common/emails/templates/5a-outstanding-issues-initial-test-notes.html
- accessibility_monitoring_platform/apps/common/templates/common/emails/templates/5b-outstanding-issues-12-week-retest-notes.html
- accessibility_monitoring_platform/apps/common/templates/common/emails/templates/5c-outstanding-issues-12-week-retest-notes-statement-only.html
- accessibility_monitoring_platform/apps/common/templates/common/emails/templates/7a-equality-body-retest-all-issues.html
- accessibility_monitoring_platform/apps/common/templates/common/emails/templates/7b-equality-body-retest-unfixed-issues.html
Trello card [#1955](https://trello.com/c/CPmTB45L/1955-reformat-issue-identifiers-in-email-templates).
> 1955: Reformat issue identifiers in email templates

- common/templates/reports_common/accessibility_report_v1_8_0__20250424.html
Trello card [#2004](https://trello.com/c/z0MYKFNg/2004-restore-text-to-report).
> 2004: Restore intro paragraph before table of statement issues in report

- accessibility_monitoring_platform/apps/dashboard/templates/dashboard/13_reports_in_qa.html
- common/templates/reports_common/accessibility_report_v1_8_0__20250424.html
* Restore intro paragraph before table of statement issues in report ([example](https://platform.accessibility-monitoring.service.gov.uk/reports/6754/report-preview/#report-your-accessibility-statement)) [#2004](https://trello.com/c/z0MYKFNg/2004-restore-text-to-report)
> v0.7.10 - Restore intro paragraph before table of statement issues in report

- accessibility_monitoring_platform/apps/audits/templates/audits/forms/equality_body_retest_page_checks.html
Trello card [#2047](https://trello.com/c/tRwI4o46/2047-label-tag-with-no-field-goes-to-page-top).
> 2047: Replace label-tag with p-tag to prevent hopping to page top on click

- accessibility_monitoring_platform/apps/simplified/forms.py
Trello card [#2055](https://trello.com/c/9GZZQlRU/2055-amend-spelling-mistake-conform-you-want-to-remove-zendest-ticket).
> 2055: Correct spelling of 'confirm'

- accessibility_monitoring_platform/apps/notifications/tests/test_utils.py
- accessibility_monitoring_platform/apps/notifications/utils.py
Trello card [#2078](https://trello.com/c/i4rqr6GI/2078-fix-link-in-qa-comment-email).
> 2078: Fix link in QA comment notification email
